# Generated by Django 2.2 on 2020-02-15 13:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('faq', '0001_squashed_0008_auto_20190904_1552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faqpluginmodel',
            name='question_group',
            field=models.ForeignKey(help_text='Question group with questions to be displayed in this plugin.', on_delete=django.db.models.deletion.PROTECT, to='faq.QuestionGroup'),
        ),
    ]
