# Generated by Django 3.2.13 on 2022-05-18 10:59

from django.db import migrations
import djangocms_text_ckeditor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('faq', '0002_auto_20200215_1336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questiontranslation',
            name='answer_text',
            field=djangocms_text_ckeditor.fields.HTMLField(blank=True, null=True, verbose_name='[TR] Answer text'),
        ),
    ]
