# Generated by Django 6.0.6 on 2026-06-19 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("faq", "0002_squashed"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="questiontranslation",
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name="questiontranslation",
            constraint=models.UniqueConstraint(
                fields=("language_code", "master"),
                name="faq_question_translation_uniq_lang",
            ),
        ),
    ]
