# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-07 10:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('faq', '0003_auto_20160704_1158'),
    ]

    def migrate_untranslated(apps, schema_editor):
        MyModel = apps.get_model('faq', 'Question')
        MyModelTranslation = apps.get_model('faq', 'QuestionTranslation')

        for object in MyModel.objects.all():
            MyModelTranslation.objects.create(
                master_id=object.pk,
                language_code='de',
                question_text=object.question_text,
                answer_text=object.answer_text,
            )

    operations = [
        migrations.CreateModel(
            name='QuestionTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('question_text', models.TextField(blank=True, null=True)),
                ('answer_text', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_tablespace': '',
                'default_permissions': (),
                'verbose_name': 'question Translation',
                'db_table': 'faq_question_translation',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='questiontranslation',
            name='master',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    related_name='translations', to='faq.Question'),
        ),
        migrations.AlterUniqueTogether(
            name='questiontranslation',
            unique_together=set([('language_code', 'master')]),
        ),

        migrations.RunPython(migrate_untranslated),
        migrations.RemoveField(
            model_name='question',
            name='question_text',
        ),
        migrations.RemoveField(
            model_name='question',
            name='answer_text',
        ),
    ]
