# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-05 11:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('faq', '0004_auto_20160707_1251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faqpluginmodel',
            name='cmsplugin_ptr',
            field=models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='faq_faqpluginmodel', serialize=False, to='cms.CMSPlugin'),
        ),
    ]
