# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-14 09:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faq', '0006_auto_20170614_0757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questiontranslation',
            name='answer_text',
            field=models.TextField(blank=True, null=True, verbose_name='[TR] Answer text'),
        ),
        migrations.AlterField(
            model_name='questiontranslation',
            name='question_text',
            field=models.TextField(blank=True, null=True, verbose_name='[TR] Question text'),
        ),
    ]
