# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2019-09-04 15:52
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.deletion
import parler.fields


class Migration(migrations.Migration):

    dependencies = [
        ('faq', '0007_auto_20170614_0929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questiontranslation',
            name='master',
            field=parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='faq.Question'),
        ),
    ]
