# Generated by Django 4.0.8 on 2023-01-06 19:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import djangocms_text_ckeditor.fields
import parler.fields
import parler.models


class Migration(migrations.Migration):

    replaces = [('events', '0002_auto_20200215_1336'), ('events', '0003_event_cancelled'), ('events', '0004_eventspluginmodel_featuredeventpluginmodel'), ('events', '0005_auto_20200608_1955'), ('events', '0006_eventspluginmodel_show_when_no_events'), ('events', '0007_auto_20200915_1526'), ('events', '0008_auto_20200915_1533'), ('events', '0009_auto_20200916_0751'), ('events', '0010_auto_20210921_1517'), ('events', '0011_auto_20210921_1547'), ('events', '0012_auto_20210921_1551'), ('events', '0013_eventcategorytranslation_teaser'), ('events', '0014_auto_20220323_1418'), ('events', '0015_auto_20220403_2158'), ('events', '0016_alter_eventcategorypluginmodel_cmsplugin_ptr_and_more')]

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0009_auto_20200426_1526'),
        ('cms', '0022_auto_20180620_1551'),
        ('events', '0001_squashed_0012_auto_20190904_1552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.ImageField(blank=True, help_text='Advertising image for this event.', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='event',
            name='special',
            field=models.BooleanField(blank=True, default=False, help_text='If this is a special event that should be emphasized on the website'),
        ),
        migrations.AddField(
            model_name='event',
            name='cancelled',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='EventsPluginModel',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='%(app_label)s_%(class)s', serialize=False, to='cms.cmsplugin')),
                ('title', models.CharField(blank=True, max_length=50, null=True)),
                ('include_specials', models.BooleanField(default=True)),
                ('include_regular', models.BooleanField(default=True)),
                ('style', models.IntegerField(choices=[(0, 'List'), (1, 'Cards')], default=0)),
                ('show_when_no_events', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='FeaturedEventPluginModel',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='%(app_label)s_%(class)s', serialize=False, to='cms.cmsplugin')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='featured_plugins', to='events.event')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='EventCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('is_featured', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='EventCategoryPluginModel',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='%(app_label)s_%(class)s', serialize=False, to='cms.cmsplugin')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plugins', to='events.eventcategory')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='EventCategoryTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('name', models.CharField(max_length=255)),
                ('description', djangocms_text_ckeditor.fields.HTMLField(blank=True, null=True)),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='events.eventcategory')),
                ('teaser', models.CharField(blank=True, max_length=400, null=True)),
            ],
            options={
                'verbose_name': 'event category Translation',
                'db_table': 'events_eventcategory_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
        migrations.RemoveField(
            model_name='event',
            name='organisators',
        ),
        migrations.AlterField(
            model_name='event',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='courses.room'),
        ),
        migrations.DeleteModel(
            name='Organise',
        ),
        migrations.AddField(
            model_name='event',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='events.eventcategory'),
        ),
        migrations.AddField(
            model_name='event',
            name='max_participants',
            field=models.IntegerField(blank=True, help_text='Defines how many people can register. Leave empty for unlimited number.', null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='registration_enabled',
            field=models.BooleanField(default=False, help_text='Gives participants of the event the possibility to register'),
        ),
        migrations.CreateModel(
            name='EventRegistration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='registrations', to='events.event')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='event_registrations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'event')},
            },
        ),
        migrations.AddField(
            model_name='event',
            name='date_to',
            field=models.DateField(blank=True, help_text='If start and end are on different days', null=True),
        ),
        migrations.AlterField(
            model_name='eventtranslation',
            name='name',
            field=models.CharField(max_length=255, verbose_name="[TR] The name of this event (e.g. 'Open Dancing')"),
        ),
        migrations.AlterField(
            model_name='eventtranslation',
            name='price_special',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='[TR] Set this only if you want a different price schema.'),
        ),
        migrations.AlterField(
            model_name='event',
            name='price_with_legi',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Leave this empty for free entrance', max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='price_without_legi',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Leave this empty for free entrance', max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='eventsteaserpluginmodel',
            name='cmsplugin_ptr',
            field=models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='%(app_label)s_%(class)s', serialize=False, to='cms.cmsplugin'),
        ),
        migrations.CreateModel(
            name='FeaturedEventCategoriesPluginModel',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='%(app_label)s_%(class)s', serialize=False, to='cms.cmsplugin')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
    ]
