# Generated by Django 2.2.10 on 2020-03-17 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20200215_1336'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='cancelled',
            field=models.BooleanField(default=False),
        ),
    ]
