# Generated by Django 2.2.12 on 2020-05-10 13:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0022_auto_20180620_1551'),
        ('events', '0003_event_cancelled'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventsPluginModel',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='events_eventspluginmodel', serialize=False, to='cms.CMSPlugin')),
                ('title', models.CharField(blank=True, max_length=50, null=True)),
                ('include_specials', models.BooleanField(default=True)),
                ('include_regular', models.BooleanField(default=True)),
                ('style', models.IntegerField(choices=[(0, 'List'), (1, 'Cards')], default=0)),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='FeaturedEventPluginModel',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='events_featuredeventpluginmodel', serialize=False, to='cms.CMSPlugin')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='featured_plugins', to='events.Event')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
    ]
