# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-04 09:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_auto_20150326_1702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='display',
            field=models.BooleanField(default=True, help_text='Defines if this event should be displayed on the website.'),
        ),
        migrations.AlterField(
            model_name='event',
            name='name',
            field=models.CharField(help_text="The name of this event (e.g. 'Freies Tanzen')", max_length=255),
        ),
        migrations.AlterField(
            model_name='event',
            name='price_with_legi',
            field=models.FloatField(blank=True, help_text='Leave this empty for free entrance', null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='price_without_legi',
            field=models.FloatField(blank=True, help_text='Leave this empty for free entrance', null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='special',
            field=models.BooleanField(default=False, help_text='If this is a special event that should be emphasized on the website'),
        ),
    ]
