# Generated by Django 3.0.6 on 2020-06-08 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_auto_20200608_1955'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventspluginmodel',
            name='show_when_no_events',
            field=models.BooleanField(default=False),
        ),
    ]
