# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-02 09:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import djangocms_text_ckeditor.fields


class Migration(migrations.Migration):
    dependencies = [
        ('events', '0006_auto_20160704_1158'),
    ]

    def migrate_untranslated(apps, schema_editor):
        MyModel = apps.get_model('events', 'Event')
        MyModelTranslation = apps.get_model('events', 'EventTranslation')

        for object in MyModel.objects.all():
            MyModelTranslation.objects.create(
                master_id=object.pk,
                language_code='de',
                description=object.description,
            )

    operations = [
        migrations.CreateModel(
            name='EventTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('description', djangocms_text_ckeditor.fields.HTMLField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'event Translation',
                'default_permissions': (),
                'db_tablespace': '',
                'managed': True,
                'db_table': 'events_event_translation',
            },
        ),
        migrations.AddField(
            model_name='eventtranslation',
            name='master',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    related_name='translations', to='events.Event'),
        ),
        migrations.AlterUniqueTogether(
            name='eventtranslation',
            unique_together={('language_code', 'master')},
        ),
        migrations.RunPython(migrate_untranslated),
        migrations.RemoveField(
            model_name='event',
            name='description',
        ),
    ]
