# Generated by Django 3.0.6 on 2020-09-15 15:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0006_eventspluginmodel_show_when_no_events'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='max_participants',
            field=models.IntegerField(blank=True, help_text='Defines how many people can register. Leave empty for unlimited number.', null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='reservation_enabled',
            field=models.BooleanField(default=False, help_text='Gives participants of the event the possibility to reserve in advance'),
        ),
        migrations.CreateModel(
            name='EventRegistration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='registrations', to='events.Event')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='event_registrations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
