# Generated by Django 6.0.5 on 2026-05-18 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_eventregistrationschedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='show_category_description',
            field=models.BooleanField(default=True, help_text='If the category description should be shown on the event detail page.'),
        ),
    ]
