# Generated by Django 6.0.6 on 2026-06-19 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0007_event_show_category_description"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="eventcategorytranslation",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="eventtranslation",
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name="eventcategorytranslation",
            constraint=models.UniqueConstraint(
                fields=("language_code", "master"),
                name="events_eventcategory_translation_uniq_lang",
            ),
        ),
        migrations.AddConstraint(
            model_name="eventtranslation",
            constraint=models.UniqueConstraint(
                fields=("language_code", "master"),
                name="events_event_translation_uniq_lang",
            ),
        ),
    ]
