# Generated by Django 3.0.6 on 2020-09-16 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_auto_20200915_1533'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='reservation_enabled',
            new_name='registration_enabled',
        ),
    ]
