# Generated by Django 6.0.6 on 2026-06-29 21:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0008_alter_eventcategorytranslation_unique_together_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="eventcategory",
            options={
                "ordering": ["position"],
                "verbose_name_plural": "event categories",
            },
        ),
    ]
