# Generated by Django 6.0.6 on 2026-06-27 15:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0008_alter_eventcategorytranslation_unique_together_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="responsible",
            field=models.ManyToManyField(
                blank=True,
                help_text="One or more people resposible for this event "
                "(e.g. organzier, teachers, DJ,...). Is used for room access code visibility.",
                related_name="events",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
