# Generated by Django 6.0.6 on 2026-06-27 15:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0008_alter_eventcategorytranslation_unique_together_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="teachers_djs",
            field=models.ManyToManyField(
                blank=True,
                help_text="Teachers, DJs, or other people who need restricted room access code visibility.",
                related_name="dj_or_teacher_events",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
