# Generated by Django 6.0.6 on 2026-06-28 20:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0009_add_teachers_djs_to_event"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="responsible",
            field=models.ManyToManyField(
                blank=True,
                help_text="One or more people resposible for this event (e.g. organzier, teachers, DJ,...). Is used for room access code visibility.",
                related_name="resposible_for_events",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
