# Generated by Django 3.2.5 on 2021-09-21 13:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0022_auto_20180620_1551'),
        ('events', '0009_auto_20200916_0751'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeaturedEventCategoriesPluginModel',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='events_featuredeventcategoriespluginmodel', serialize=False, to='cms.cmsplugin')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
        migrations.AddField(
            model_name='eventcategorytranslation',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='eventcategorytranslation',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
    ]
