# Generated by Django 3.2.5 on 2021-09-21 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0010_auto_20210921_1517'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventcategorytranslation',
            name='image',
        ),
        migrations.RemoveField(
            model_name='eventcategorytranslation',
            name='is_featured',
        ),
    ]
