# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-25 17:17
from __future__ import unicode_literals

from django.db import migrations, models


def migrate_untranslated(apps, schema_editor):
    events = apps.get_model('events', 'Event')
    event_translations = apps.get_model('events', 'EventTranslation')

    for item in events.objects.all():
        for code in ['de', 'en']:
            db_item = event_translations.objects.filter(
                master_id=item.pk,
                language_code=code,
            )

            if db_item.exists():
                db_item.update(
                    name=item.name,
                    price_special=item.price_special,
                )
            else:
                event_translations.objects.create(
                    master_id=item.pk,
                    language_code=code,
                    name=item.name,
                    price_special=item.price_special,
                )


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0010_auto_20170614_0929'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['-date', '-time_from']},
        ),
        migrations.AddField(
            model_name='eventtranslation',
            name='name',
            field=models.CharField(default='Untranslated', max_length=255, verbose_name="[TR] The name of this event (e.g. 'Freies Tanzen')"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='eventtranslation',
            name='price_special',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Set this only if you want a different price schema.'),
        ),
        migrations.RunPython(migrate_untranslated),
        migrations.RemoveField(
            model_name='event',
            name='name',
        ),
        migrations.RemoveField(
            model_name='event',
            name='price_special',
        ),
    ]
