# Generated by Django 3.2.5 on 2021-09-21 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0011_auto_20210921_1547'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventcategory',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='eventcategory',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
    ]
