# Generated by Django 6.0.7 on 2026-07-21 19:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0011_alter_event_responsible"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="published",
            field=models.BooleanField(
                default=True,
                help_text="Defines if this event's page can be viewed. Unpublished events are only visible to staff who can view events.",
            ),
        ),
    ]
