# Generated by Django 3.2.5 on 2021-09-21 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0012_auto_20210921_1551'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventcategorytranslation',
            name='teaser',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
