# Generated by Django 3.2.12 on 2022-04-03 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0014_auto_20220323_1418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='price_with_legi',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Leave this empty for free entrance', max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='price_without_legi',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Leave this empty for free entrance', max_digits=6, null=True),
        ),
    ]
