drop table if exists auditing_problem;
alter table cms_cmsplugin modify position smallint not null;
alter table cms_cmsplugin modify depth int not null;
alter table cms_cmsplugin modify numchild int not null;
alter table cms_treenode modify depth int not null;
alter table cms_treenode modify numchild int not null;
drop table if exists cmsplugin_filer_image_filerimage;
drop table if exists cmsplugin_filer_link_filerlinkplugin;
alter table django_celery_beat_periodictask modify total_run_count int not null;
alter table django_celery_beat_periodictask modify priority int;
alter table django_celery_beat_periodictask modify expire_seconds int;
alter table djcelery_periodictask modify total_run_count int not null;
alter table easy_thumbnails_thumbnaildimensions modify width int;
alter table easy_thumbnails_thumbnaildimensions modify height int;
alter table filer_folder modify lft int not null;
alter table filer_folder modify rght int not null;
alter table filer_folder modify tree_id int not null;
alter table filer_folder modify level int not null;
alter table menus_cachekey modify site int not null;