from django.conf.urls import url

from payment import views

app_name = 'payment'
urlpatterns = [
    url(r'^auth/counterpayment/(?P<usi>[a-zA-Z0-9]{6})/details/$',
        views.CounterPaymentDetailView.as_view(),
        name='counterpayment_detail'),
    url(r'^auth/counterpayment/$',
        views.CounterPaymentIndexView.as_view(),
        name='counterpayment_index'),
    url(r'^payment/(?P<usi>[a-zA-Z0-9]{6})/payed/$', views.VoucherPaymentSuccessView.as_view(),
        name='voucherpayment_success'),
    url(r'^payment/(?P<usi>[a-zA-Z0-9]{6})/$', views.VoucherPaymentIndexView.as_view(),
        name='voucherpayment_index'),
    url(r'^auth/coursepayment/$',
        views.CoursePaymentIndexView.as_view(),
        name='coursepayment_index'),
    url(r'^auth/coursepayment/(?P<course>[0-9]*)/$', views.CoursePaymentDetailView.as_view(),
        name='coursepayment_detail'),
    url(r'^auth/coursepayment/(?P<course>[0-9]*)/export/csv$',
        views.CoursePaymentExportCsv.as_view(),
        name='coursepayment_export_csv'),
    url(r'^auth/coursepayment/(?P<course>[0-9]*)/export/vcard$',
        views.CoursePaymentExportVCard.as_view(),
        name='coursepayment_export_vcard'),
    url(r'^auth/coursepayment/(?P<course>[0-9]*)/export/$',
        views.CoursePaymentExportExcel.as_view(),
        name='coursepayment_export'),
    url(r'^auth/coursepayment/(?P<course>[0-9]*)/(?P<usi>[a-zA-Z0-9]{6})/$',
        views.CoursePaymentConfirm.as_view(),
        name='coursepayment_confirm'),
    url(r'^auth/coursepayment/(?P<course>[0-9]*)/(?P<usi>[a-zA-Z0-9]{6})/paid/$',
        views.CoursePaymentConfirm.as_view(),
        name='coursepayment_payed'),
    url(r'^auth/finance/(?P<offering>[0-9]*)/detail/$', views.OfferingFinanceDetailView.as_view(),
        name='offering_finance_detail_view'),
    url(r'^auth/finance/(?P<offering>[0-9]*)/subscribers/$', views.OfferingFinanceOverviewSubscribers.as_view(),
        name='offering_finance_overview_subscribers'),
    url(r'^auth/finance/(?P<offering>[0-9]*)/teachers/$', views.OfferingFinanceOverviewTeachers.as_view(),
        name='offering_finance_overview_teachers'),
    url(r'^auth/finance/$', views.OfferingFinanceIndexView.as_view(),
        name='offering_finance_index_view'),
    url(r'^auth/finance/account/index/$', views.AccountFinanceIndexView.as_view(),
        name='account_finance_index_view'),
    url(r'^auth/finance/account/detail/$', views.AccountFinanceDetailView.as_view(),
        name='account_finance_detail_view'),
]
