FROM python:3.7-alpine
MAINTAINER martin.zellner@gmail.com

# Legacy Dockerfile
# Used for the deploy on the TQ server as well as for local development
# For the latter, consider migrating to a single Dockerfile maybe?

# make sure to have the latest package index
RUN rm -rf /var/cache/apk/* && \
    rm -rf /tmp/*

RUN apk update

# Postgres
RUN apk add --no-cache postgresql-libs && \
    apk add --no-cache --virtual .build-deps gcc postgresql-dev musl-dev && \
    pip3 install psycopg2==2.8.5 && \
    apk del .build-deps

# Pillow
RUN apk add --no-cache zlib jpeg && \
    apk add --no-cache libxml2-dev libxslt-dev python-dev && \
    apk add --no-cache --virtual .build-deps \
    build-base jpeg-dev zlib-dev && \
    LIBRARY_PATH=/lib:/usr/lib pip3 install Pillow==7.1.2 && \
    apk del .build-deps

# pyreverse: generate UML diagrams in comfortable formats
RUN apk add --no-cache graphviz && \
    apk add --no-cache ttf-dejavu

# Cryptography
RUN apk add --no-cache openssl && \
    apk add --no-cache --virtual .build-deps \
    build-base openssl-dev libffi-dev && \
    LIBRARY_PATH=/lib:/usr/lib pip3 install cryptography==2.9.2 && \
    apk del .build-deps

# gettext (needed to compile language files on the server)
RUN apk add --no-cache gettext-dev

# Python3
RUN apk add --no-cache python3-dev

# make (needed for building sphinx documentation)
RUN apk add --no-cache make

ADD requirements.txt /app/requirements.txt

RUN apk add --no-cache --virtual .build-deps build-base && \
    pip3 install --upgrade -r /app/requirements.txt && \
    apk del .build-deps

WORKDIR /app/
