# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-02-15 11:01
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


# Functions from the following migrations need manual copying.
# Move them and any dependencies into this file, then update the
# RunPython operations to refer to the local versions:
# organisation.migrations.0004_function_users

def migrate_function(apps, schema_editor):
    FunctionModel = apps.get_model('organisation', 'Function')

    for function in FunctionModel.objects.all():
        function.users.add(function.user)

class Migration(migrations.Migration):

    replaces = [('organisation', '0001_initial'), ('organisation', '0002_auto_20151013_1220'), ('organisation', '0003_auto_20160704_1158'), ('organisation', '0004_function_users'), ('organisation', '0005_remove_function_user')]

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Function',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('active', models.BooleanField(default=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('position', models.PositiveSmallIntegerField(default=0, verbose_name='Position')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('users', models.ManyToManyField(blank=True, related_name='functions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['position'],
            },
        ),
        migrations.RunPython(
            code=migrate_function,
        ),
        migrations.RemoveField(
            model_name='function',
            name='user',
        ),
    ]
