# Generated by Django 4.0.7 on 2022-10-28 15:53

from django.db import migrations, models
import django.db.models.deletion
import parler.fields
import parler.models

def migrate_name(apps, schema_editor) -> None:
    model = apps.get_model('organisation', 'Function')
    model_translation = apps.get_model('organisation', 'FunctionTranslation')

    for instance in model.objects.all():
        model_translation.objects.create(master_id=instance.pk, language_code='en', name=instance.temp_name)
        model_translation.objects.create(master_id=instance.pk, language_code='de', name=instance.temp_name)

class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0001_squashed_0005_remove_function_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='FunctionTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('name', models.CharField(help_text='The name of the ressort. E.g. Event Management', max_length=64, verbose_name='[TR] Name')),
                ('master', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='organisation.function')),
            ],
            options={
                'verbose_name': 'function Translation',
                'db_table': 'organisation_function_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
        migrations.RenameField(
            model_name='function',
            old_name='name',
            new_name='temp_name'
        ),
        migrations.RunPython(
            code=migrate_name,
        ),
        migrations.RemoveField(
            model_name='function',
            name='temp_name',
        ),
        migrations.AlterModelOptions(
            name='function',
            options={'ordering': ['email']},
        ),
        migrations.RemoveField(
            model_name='function',
            name='active',
        ),
        migrations.RemoveField(
            model_name='function',
            name='position',
        ),
    ]
