# Generated by Django 6.0.6 on 2026-06-19 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organisation", "0001_squashed"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="functiontranslation",
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name="functiontranslation",
            constraint=models.UniqueConstraint(
                fields=("language_code", "master"),
                name="organisation_function_translation_uniq_lang",
            ),
        ),
    ]
