# Generated by Django 4.0.8 on 2022-12-14 21:29

from django.db import migrations
import django.db.models.deletion
import parler.fields


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0002_alter_function_options_remove_function_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='functiontranslation',
            name='master',
            field=parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='organisation.function'),
        ),
    ]
