# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-05 12:49
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('organisation', '0003_auto_20160704_1158'),
    ]

    def migrate_function(apps, schema_editor):
        FunctionModel = apps.get_model('organisation', 'Function')

        for function in FunctionModel.objects.all():
            function.users.add(function.user)

    operations = [
        migrations.AddField(
            model_name='function',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='functions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RunPython(migrate_function)
    ]
