# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-05 13:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0004_function_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='function',
            name='user',
        ),
    ]
