# Generated by Django 2.2.11 on 2020-03-31 19:36

from django.db import migrations, models
import django.db.models.deletion
import storages.backends.s3boto3


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_squashed_0016_auto_20190425_1717'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostfinanceFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('file', models.FileField(storage=storages.backends.s3boto3.S3Boto3Storage(bucket_name='postfinance'), upload_to='')),
                ('processed', models.BooleanField(default=False)),
                ('downloaded_at', models.DateTimeField()),
            ],
            options={
                'ordering': ['-downloaded_at'],
            },
        ),
        migrations.AddField(
            model_name='payment',
            name='file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='payment.PostfinanceFile'),
        ),
    ]
