# Generated by Django 6.0.6 on 2026-06-27 08:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0077_course_payrexx_enabled_alter_subscribe_paymentmethod"),
        ("payment", "0003_alter_financefile_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="filename",
            field=models.CharField(blank=True, default="", max_length=300),
        ),
        migrations.CreateModel(
            name="PayrexxGateway",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("card", "Card (Visa / Mastercard)"),
                            ("twint", "TWINT"),
                        ],
                        max_length=10,
                    ),
                ),
                ("gateway_id", models.IntegerField(unique=True)),
                ("link", models.URLField(max_length=500)),
                ("gross_amount", models.DecimalField(decimal_places=2, max_digits=9)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                            ("expired", "Expired"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "payrexx_transaction_id",
                    models.IntegerField(blank=True, null=True, unique=True),
                ),
                (
                    "payment",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="payrexx_gateway",
                        to="payment.payment",
                    ),
                ),
                (
                    "subscription",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payrexx_gateways",
                        to="courses.subscribe",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
