# Generated by Django 2.2.12 on 2020-04-25 15:51

from django.db import migrations, models
import tq_website.storages


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0004_auto_20200425_1508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postfinancefile',
            name='file',
            field=models.FileField(storage=tq_website.storages.FinanceStorage(), upload_to=''),
        ),
    ]
