# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-04 09:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0004_auto_20160701_1349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='state',
            field=models.CharField(choices=[('new', 'new'), ('manual', 'manual'), ('processed', 'processed')], default='new', max_length=50),
        ),
        migrations.AlterField(
            model_name='payment',
            name='type',
            field=models.CharField(choices=[('subscription_payment', 'subscription payment'), ('subscription_payment_to_reimburse', 'subscription payment (to reimburse)'), ('course_payment_transfer', 'course payment transfer'), ('irrelevant', 'irrelevant'), ('unknown', 'unknown')], default='unknown', help_text='The type is auto-detected when the state is NEW, otherwise the detector will not touch this field anymore.', max_length=50, verbose_name='type (detected)'),
        ),
    ]
