# Generated by Django 3.2.12 on 2022-04-02 11:06

from django.db import migrations, models
import django.db.models.deletion
import tq_website.storages


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0005_auto_20200425_1551'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PostfinanceFile',
            new_name='FinanceFile',
        ),
        migrations.AddField(
            model_name='FinanceFile',
            name='type',
            field=models.CharField(choices=[('postfinance_xml', 'Postfinance XML'), ('zkb_csv', 'ZKB CSV')],
                                   default='postfinance_xml', max_length=32),
        ),
        migrations.AlterField(
            model_name='financefile',
            name='downloaded_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
