# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-20 22:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0041_subscribe_price_to_pay'),
        ('payment', '0006_coursepayment'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentReminder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True, help_text='The date when the reminder mail was sent to the subscriber.')),
                ('mail', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='post_office.Email')),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_reminders', to='courses.Subscribe')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
