# Generated by Django 3.2.12 on 2022-04-02 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0006_auto_20220402_1306'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='financefile',
            options={'ordering': ['-created_at']},
        ),
        migrations.RenameField(
            model_name='financefile',
            old_name='downloaded_at',
            new_name='created_at',
        ),
    ]
