# Generated by Django 3.2.12 on 2022-04-03 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0007_auto_20220402_1326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursepayment',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=9),
        ),
        migrations.AlterField(
            model_name='payment',
            name='amount_to_reimburse',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=9),
        ),
        migrations.AlterField(
            model_name='subscriptionpayment',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
