# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-27 11:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0008_auto_20170227_1000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='state',
            field=models.CharField(choices=[('new', 'new'), ('manual', 'manual'), ('matched', 'matched'), ('processed', 'processed')], default='new', max_length=50),
        ),
    ]
