# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-11 15:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0010_auto_20170511_1554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='credit_debit',
            field=models.CharField(choices=[('unknown', 'unknown'), ('credit', 'credit (incoming money)'), ('debit', 'debit (outgoing money)')], default='unknown', help_text='If this transaction is a credit or a debit.', max_length=50, verbose_name='credit/debit'),
        ),
    ]
