# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-06 15:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0011_auto_20170511_1556'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ['date']},
        ),
    ]
