# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-14 07:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0012_auto_20170606_1522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursepayment',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='course_payments', to='courses.Course'),
        ),
        migrations.AlterField(
            model_name='coursepayment',
            name='payment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='course_payments', to='payment.Payment'),
        ),
        migrations.AlterField(
            model_name='subscriptionpayment',
            name='payment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscription_payments', to='payment.Payment'),
        ),
        migrations.AlterField(
            model_name='subscriptionpayment',
            name='subscription',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscription_payments', to='courses.Subscribe'),
        ),
    ]
