# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-10-22 09:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0013_auto_20170614_0757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='remittance_user_string',
            field=models.CharField(max_length=600),
        ),
    ]
