# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-05-07 17:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0014_auto_20171022_0915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='state',
            field=models.CharField(choices=[('new', 'new'), ('manual', 'manual'), ('matched', 'matched'), ('processed', 'processed'), ('archive', 'archive')], default='new', max_length=50),
        ),
    ]
