# Generated by Django 3.0.6 on 2020-06-05 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
