# Generated by Django 3.2.12 on 2022-03-23 13:18

from django.db import migrations, models
import partners.models.partner


class Migration(migrations.Migration):
    dependencies = [
        ('partners', '0002_partner_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=partners.models.partner.upload_path,
                                    verbose_name='Image'),
        ),
    ]
