# Generated by Django 6.0.6 on 2026-06-19 10:49

from django.db import migrations, models

_TRANSLATION_TABLES = [
    "partners_partner_translation",
]

_NEW_CONSTRAINT_NAMES = [
    "partners_partner_translation_uniq_lang",
]

_DROP_OLD_UNIQUE_CONSTRAINTS_SQL = """
DO $$
DECLARE r RECORD;
BEGIN
    FOR r IN (
        SELECT c.conname, t.relname
        FROM pg_constraint c
        JOIN pg_class t ON c.conrelid = t.oid
        WHERE t.relname IN ({tables})
          AND c.contype = 'u'
          AND c.conname NOT IN ({new_names})
    ) LOOP
        EXECUTE format('ALTER TABLE %%I DROP CONSTRAINT %%I', r.relname, r.conname);
    END LOOP;
END $$;
""".format(
    tables=", ".join(f"'{t}'" for t in _TRANSLATION_TABLES),
    new_names=", ".join(f"'{n}'" for n in _NEW_CONSTRAINT_NAMES),
)


class Migration(migrations.Migration):

    dependencies = [
        ("partners", "0003_resize_partner_image"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterUniqueTogether(
                    name="partnertranslation",
                    unique_together=set(),
                ),
            ],
            database_operations=[
                migrations.RunSQL(
                    sql=_DROP_OLD_UNIQUE_CONSTRAINTS_SQL,
                    reverse_sql=migrations.RunSQL.noop,
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="partnertranslation",
            constraint=models.UniqueConstraint(
                fields=("language_code", "master"),
                name="partners_partner_translation_uniq_lang",
            ),
        ),
    ]
