# Generated by Django 6.0.6 on 2026-06-19 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("partners", "0003_resize_partner_image"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="partnertranslation",
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name="partnertranslation",
            constraint=models.UniqueConstraint(
                fields=("language_code", "master"),
                name="partners_partner_translation_uniq_lang",
            ),
        ),
    ]
