# Generated by Django 2.2.11 on 2020-04-15 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('email_system', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='generatedtqemail',
            options={'verbose_name': 'Generated Email'},
        ),
        migrations.AlterModelOptions(
            name='tqemail',
            options={'verbose_name': 'Email'},
        ),
        migrations.AlterModelOptions(
            name='tqemailtranslation',
            options={'default_permissions': (), 'managed': True, 'verbose_name': 'Email Translation'},
        ),
    ]
