# Generated by Django 5.0.4 on 2024-05-16 22:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("email_system", "0001_squashed"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="groupemail",
            name="sent_at",
        ),
    ]
