# Generated by Django 5.0.4 on 2024-05-10 14:50

from django.db import migrations, models
from email_system.models import GroupEmail
from email_system.models.choices import GroupEmailState

def set_state() -> None:
    group_emails: list[GroupEmail] = GroupEmail.objects.all()
    for group_email in group_emails:
        if group_email.sent_at is not None:
            group_email.state = GroupEmailState.SENT
            group_email.save()

class Migration(migrations.Migration):

    dependencies = [
        ("email_system", "0001_squashed"),
    ]

    operations = [
        migrations.AddField(
            model_name="groupemail",
            name="state",
            field=models.CharField(
                choices=[("draft", "Draft"), ("queued", "Queued"), ("sent", "Sent")],
                db_index=True,
                default="draft",
                max_length=10,
            ),
        ),
        migrations.RunPython(set_state),
    ]
