# Generated by Django 5.0.4 on 2024-05-10 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("email_system", "0001_squashed"),
    ]

    operations = [
        migrations.AddField(
            model_name="groupemail",
            name="state",
            field=models.CharField(
                choices=[("draft", "Draft"), ("queued", "Queued"), ("sent", "Sent")],
                db_index=True,
                default="draft",
                max_length=10,
            ),
        ),
    ]
