# Generated by Django 5.0.4 on 2024-05-10 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("email_system", "0002_groupemail_state"),
    ]

    operations = [
        migrations.DeleteModel(
            name="GeneratedIndividualEmail",
        ),
    ]
