# Generated by Django 5.0.9 on 2024-10-19 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("email_system", "0002_remove_groupemail_sent_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="groupemail",
            name="schedule_send",
            field=models.DateTimeField(
                blank=True,
                help_text="When the email should be dispatched automatically. Won't be dispatched if empty.",
                null=True,
            ),
        ),
    ]
