# Generated by Django 2.2.11 on 2020-04-15 14:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post_office', '0008_attachment_headers'),
        ('auth', '0011_update_proxy_permissions'),
        ('email_system', '0002_auto_20200415_1300'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneratedIndividualEmail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='generated_group_emails', to='post_office.Email')),
            ],
            options={
                'verbose_name': 'Generated individual Email',
            },
        ),
        migrations.RenameModel(
            old_name='TQEmailTranslation',
            new_name='GroupEmailTranslation',
        ),
        migrations.AlterModelTable(
            name='groupemailtranslation',
            table='email_system_groupemail_translation',
        ),
        migrations.RenameModel(
            old_name='TQEmail',
            new_name='GroupEmail',
        ),
        migrations.DeleteModel(
            name='GeneratedTQEmail',
        ),
        migrations.AddField(
            model_name='generatedindividualemail',
            name='source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_emails', to='email_system.GroupEmail'),
        ),
    ]
