# Generated by Django 5.0.4 on 2024-05-14 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("email_system", "0002_groupemail_state"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="generatedindividualemail",
            options={"verbose_name": "Generated individual emails"},
        ),
    ]
