# Generated by Django 6.0.6 on 2026-06-19 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("email_system", "0003_groupemail_schedule_send"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="groupemailtranslation",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="tqemailaddresstranslation",
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name="groupemailtranslation",
            constraint=models.UniqueConstraint(
                fields=("language_code", "master"),
                name="email_system_groupemail_translation_uniq_lang",
            ),
        ),
        migrations.AddConstraint(
            model_name="tqemailaddresstranslation",
            constraint=models.UniqueConstraint(
                fields=("language_code", "master"),
                name="email_system_tqemailaddress_translation_uniq_lang",
            ),
        ),
    ]
