# Generated by Django 2.2.12 on 2020-04-22 19:41

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import email_system.models.unsubscribe_code
import parler.fields
import parler.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('email_system', '0003_auto_20200415_1411'),
    ]

    operations = [
        migrations.CreateModel(
            name='TqEmailAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_address', models.EmailField(max_length=254)),
            ],
            options={
                'abstract': False,
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.AlterModelOptions(
            name='groupemail',
            options={'verbose_name': 'Group Email'},
        ),
        migrations.AlterModelOptions(
            name='groupemailtranslation',
            options={'default_permissions': (), 'managed': True, 'verbose_name': 'Group Email Translation'},
        ),
        migrations.CreateModel(
            name='UnsubscribeCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default=email_system.models.unsubscribe_code._generate_code, max_length=36)),
                ('generated_at', models.DateTimeField(default=datetime.datetime.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unsubscribe_codes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='groupemail',
            name='reply_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='group_email_reply_tos', to='email_system.TqEmailAddress', verbose_name='Reply-To address'),
        ),
        migrations.CreateModel(
            name='TqEmailAddressTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('description', models.CharField(blank=True, max_length=200, null=True, verbose_name='Description')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='email_system.TqEmailAddress')),
            ],
            options={
                'verbose_name': 'tq email address Translation',
                'db_table': 'email_system_tqemailaddress_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
    ]
