# Generated by Django 6.0.6 on 2026-06-28 06:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("email_system", "0004_alter_groupemailtranslation_unique_together_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="groupemail",
            name="include_unsubscribe",
            field=models.BooleanField(
                default=False,
                help_text="Add List-Unsubscribe headers and an unsubscribe link to the email. REQUIRED for marketing/newsletter emails.",
                verbose_name="Include unsubscribe",
            ),
        ),
    ]
