# Generated by Django 2.2.12 on 2020-04-25 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('email_system', '0004_auto_20200422_1941'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tqemailaddress',
            options={'verbose_name': 'Email Address', 'verbose_name_plural': 'Email Addresses'},
        ),
        migrations.AlterModelOptions(
            name='tqemailaddresstranslation',
            options={'default_permissions': (), 'managed': True, 'verbose_name': 'Email Address Translation'},
        ),
    ]
