# Generated by Django 6.0.6 on 2026-06-29 21:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("email_system", "0005_include_unsubscribe"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="generatedindividualemail",
            options={
                "verbose_name": "Generated individual Email",
                "verbose_name_plural": "Generated individual emails",
            },
        ),
    ]
