# Generated by Django 2.2.12 on 2020-04-27 19:01

from django.db import migrations, models
import djangocms_text_ckeditor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('email_system', '0005_auto_20200425_1508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupemailtranslation',
            name='message',
            field=djangocms_text_ckeditor.fields.HTMLField(default='', help_text='Content of the email', verbose_name='Message'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='groupemailtranslation',
            name='subject',
            field=models.CharField(default='<empty>', max_length=100, verbose_name='Subject'),
            preserve_default=False,
        ),
    ]
