# Generated by Django 6.0.7 on 2026-10-03 07:41

from django.db import migrations

# Databases created with old django-post-office versions store these JSON fields
# as text columns (post_office later rewrote its migrations to models.JSONField,
# so Django never converted them). JSON key lookups, e.g. in the post_office
# admin, fail on text columns. Fresh databases already have jsonb and are skipped.
_CONVERT_TEXT_COLUMNS_TO_JSONB_SQL = """
DO $$
DECLARE r RECORD;
BEGIN
    FOR r IN (
        SELECT table_name, column_name
        FROM information_schema.columns
        WHERE table_schema = current_schema()
          AND data_type = 'text'
          AND (table_name, column_name) IN (
              ('post_office_email', 'headers'),
              ('post_office_email', 'context'),
              ('post_office_attachment', 'headers')
          )
    ) LOOP
        EXECUTE format(
            'ALTER TABLE %I ALTER COLUMN %I TYPE jsonb USING %I::jsonb',
            r.table_name, r.column_name, r.column_name
        );
    END LOOP;
END $$;
"""


class Migration(migrations.Migration):
    dependencies = [
        ("email_system", "0006_alter_generatedindividualemail_options"),
        ("post_office", "0014_alter_email_recipient_delivery_status_and_more"),
    ]

    operations = [
        migrations.RunSQL(
            sql=_CONVERT_TEXT_COLUMNS_TO_JSONB_SQL,
            reverse_sql=migrations.RunSQL.noop,
        ),
    ]
