FROM python:3.5-alpine
MAINTAINER martin.zellner@gmail.com

# MySQL
RUN apk add --no-cache mariadb-client-libs && \
    apk add --no-cache --virtual .build-deps \
    build-base mariadb-dev && \
    pip3 install mysqlclient==1.3.7 && \
    apk del .build-deps

# Pillow
RUN apk add --no-cache zlib jpeg && \
    apk add --no-cache --virtual .build-deps \
    build-base jpeg-dev zlib-dev && \
    LIBRARY_PATH=/lib:/usr/lib pip3 install Pillow==3.2.0 && \
    apk del .build-deps

# Cryptography
RUN apk add --no-cache openssl && \
    apk add --no-cache --virtual .build-deps \
    build-base openssl-dev libffi-dev && \
    LIBRARY_PATH=/lib:/usr/lib pip3 install cryptography==1.7.1 && \
    apk del .build-deps

# Cairo (cairocffi 0.7.2 does not work!!)
RUN apk add --no-cache py-cffi libffi cairo && \
    apk add --no-cache --virtual .build-deps \
    build-base libffi-dev && \
    pip3 install cffi==1.10.0 && \
    pip3 install cairocffi==0.8.0 && \
    apk del .build-deps

# Cairo
RUN apk add --no-cache libxml2-dev libxslt-dev && \
    apk add --no-cache --virtual .build-deps \
    build-base libxml2-dev libxslt-dev && \
    pip3 install cairosvg==2.0.2 && \
    apk del .build-deps

# Python3
RUN apk add --no-cache python3-dev

ADD configurations/python-requirements.txt /webapps/tq_website/configurations/python-requirements.txt

RUN pip3 install --upgrade -r /webapps/tq_website/configurations/python-requirements.txt

WORKDIR /webapps/tq_website/