FROM python:3.5-alpine
MAINTAINER martin.zellner@gmail.com

# MySQL
RUN apk add --no-cache mariadb-client-libs && \
    apk add --no-cache --virtual .build-deps \
    build-base mariadb-dev && \
    pip3 install mysqlclient==1.3.7 && \
    apk del .build-deps

# Pillow
RUN apk add --no-cache zlib jpeg && \
    apk add --no-cache --virtual .build-deps \
    build-base jpeg-dev zlib-dev && \
    LIBRARY_PATH=/lib:/usr/lib pip3 install Pillow==3.2.0 && \
    apk del .build-deps

# pyreverse: generate UML diagrams in comfortable formats
RUN apk add --no-cache graphviz && \
    apk add --no-cache ttf-dejavu

# Cryptography
RUN apk add --no-cache openssl && \
    apk add --no-cache --virtual .build-deps \
    build-base openssl-dev libffi-dev && \
    LIBRARY_PATH=/lib:/usr/lib pip3 install cryptography==1.7.1 && \
    LIBRARY_PATH=/lib:/usr/lib pip3 install cffi && \
    apk del .build-deps

# gettext (needed to compile language files on the server)
RUN apk add --no-cache gettext-dev

# Python3
RUN apk add --no-cache python3-dev

ADD configurations/python-requirements.txt /webapps/tq_website/configurations/python-requirements.txt

RUN apk add --no-cache --virtual .build-deps build-base && \
    pip3 install --upgrade -r /webapps/tq_website/configurations/python-requirements.txt && \
    apk del .build-deps

WORKDIR /webapps/tq_website/
