FROM python:3.7-alpine
MAINTAINER martin.zellner@gmail.com

# make sure to have the latest package index
RUN rm -rf /var/cache/apk/* && \
    rm -rf /tmp/*

RUN apk update

# MySQL
RUN apk add --no-cache mariadb-connector-c-dev mariadb-connector-c && \
    apk add --no-cache --virtual .build-deps \
    build-base mariadb-dev && \
    pip3 install mysqlclient==1.4.6 && \
    apk del .build-deps

# Postgres
RUN apk add --no-cache postgresql-libs && \
    apk add --no-cache --virtual .build-deps gcc postgresql-dev musl-dev && \
    pip3 install psycopg2==2.8.4 && \
    apk del .build-deps

# Pillow
RUN apk add --no-cache zlib jpeg && \
    apk add --no-cache --virtual .build-deps \
    build-base jpeg-dev zlib-dev && \
    LIBRARY_PATH=/lib:/usr/lib pip3 install Pillow==3.2.0 && \
    apk del .build-deps

# pyreverse: generate UML diagrams in comfortable formats
RUN apk add --no-cache graphviz && \
    apk add --no-cache ttf-dejavu

# Cryptography
RUN apk add --no-cache openssl && \
    apk add --no-cache --virtual .build-deps \
    build-base openssl-dev libffi-dev && \
    LIBRARY_PATH=/lib:/usr/lib pip3 install cryptography==2.8 && \
    apk del .build-deps

# gettext (needed to compile language files on the server)
RUN apk add --no-cache gettext-dev

# Python3
RUN apk add --no-cache python3-dev

# make (needed for building sphinx documentation)
RUN apk add --no-cache make

ADD configurations/python-requirements.txt /webapps/tq_website/configurations/python-requirements.txt

RUN apk add --no-cache --virtual .build-deps build-base && \
    pip3 install --upgrade -r /webapps/tq_website/configurations/python-requirements.txt && \
    apk del .build-deps

WORKDIR /webapps/tq_website/
