# Generated by Django 4.1.5 on 2023-02-19 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_squashed'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='zemis_number',
            field=models.CharField(blank=True, help_text='Every registered foreigner in switzerland gets a ZEMIS number.', max_length=255, null=True),
        ),
    ]
