# Generated by Django 4.1.7 on 2023-02-21 21:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0003_userprofile_zemis_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="offering",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="courses.offering"
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="period",
            field=models.ForeignKey(
                blank=True,
                help_text="You can set a custom period for this course here. If this is left empty, the period from the offering is taken. ",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="courses.period",
            ),
        ),
    ]
