# Generated by Django 2.2 on 2020-02-27 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_auto_20200219_1613'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CurrentCourse',
        ),
        migrations.DeleteModel(
            name='PlannedCourse',
        ),
        migrations.AlterModelOptions(
            name='offering',
            options={'ordering': ['-period__date_from', 'name']},
        ),
    ]
