# Generated by Django 2.2.11 on 2020-04-13 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_auto_20200401_1236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(choices=[('m', 'male'), ('w', 'female')], default=None, max_length=1, null=True),
        ),
    ]
