# Generated by Django 4.2.1 on 2023-07-28 15:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0007_remove_userprofile_default_hourly_wage_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="offering",
            name="group_into_sections",
            field=models.BooleanField(
                default=True,
                help_text="If true, a separate section for each month / day of week is displayed on the course page.",
            ),
        ),
        migrations.AddField(
            model_name="offering",
            name="limit_courses_per_section",
            field=models.SmallIntegerField(
                blank=True,
                help_text="If set, only that many courses are shown for each section of the course list. The remaining courses will be shown when expanding the section.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="offering",
            name="display",
            field=models.BooleanField(
                default=False,
                help_text="Defines if this offering should be displayed on the Website.",
            ),
        ),
    ]
