# Generated by Django 4.2.1 on 2023-07-28 22:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0008_offering_group_into_sections_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="offering",
            options={"ordering": ["-period__date_to", "name"]},
        ),
        migrations.AlterField(
            model_name="offering",
            name="period",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="courses.period"
            ),
        ),
    ]
