# Generated by Django 4.2.1 on 2023-08-06 15:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0009_alter_offering_options_alter_offering_period"),
    ]

    operations = [
        migrations.AlterField(
            model_name="teach",
            name="hourly_wage",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Please leave this field empty! The wage is calculated based "
                "on the number of courses taught or the fixed wage set in the "
                "teachers profile.",
                max_digits=6,
                null=True,
            ),
        ),
        migrations.DeleteModel(
            name="TeachLesson",
        ),
    ]
