# Generated by Django 3.2.8 on 2021-10-27 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0011_modified_sql_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscribe',
            name='lead_follow',
            field=models.CharField(choices=[('l', 'lead'), ('f', 'follow'), ('n', 'no preference')], default='n', max_length=1),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(choices=[('m', 'male'), ('w', 'female'), ('d', 'diverse')], default=None, max_length=1, null=True),
        ),
    ]
