# Generated by Django 4.2.4 on 2023-09-12 11:06

import datetime

import django.db.models.deletion
from django.db import migrations, models

from courses.models import RegistrationPeriod


def default_registration_period() -> RegistrationPeriod:
    registration_period, _ = RegistrationPeriod.objects.get_or_create(
        name="Open until course start",
        deadline=datetime.timedelta(),
        preregistration=datetime.timedelta(),
    )
    return registration_period.id


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0011_alter_bankaccount_iban_alter_userprofile_address_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="RegistrationPeriod",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30, unique=True)),
                (
                    "start",
                    models.DateTimeField(
                        default=datetime.date(1, 1, 1),
                        help_text="People will be able to sign up for courses, "
                        "starting with this point in time.",
                    ),
                ),
                (
                    "deadline",
                    models.DurationField(
                        default=datetime.timedelta(days=-1, seconds=43200),
                        help_text="The registration deadline is relative to the start "
                        "of the first lesson. A negative value means, the registration "
                        "deadline is before the first lesson. If you for example want "
                        "to allow sign-ups until the second week, you can set this "
                        "value to 7 days.",
                    ),
                ),
                (
                    "preregistration",
                    models.DurationField(
                        default=datetime.timedelta(days=1),
                        help_text="People eligible for preregistration (e.g. "
                        "participants of a preceding course) are allowed to sign up "
                        "this much before the general registration starts.",
                    ),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="course",
            name="active",
        ),
        migrations.RemoveField(
            model_name="course",
            name="preceding_courses",
        ),
        migrations.RemoveField(
            model_name="offering",
            name="active",
        ),
        migrations.RemoveField(
            model_name="offering",
            name="opens_soon",
        ),
        migrations.AddField(
            model_name="coursetype",
            name="successor",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="predecessor",
                to="courses.coursetype",
            ),
        ),
        migrations.DeleteModel(
            name="CourseSuccession",
        ),
        migrations.AddField(
            model_name="course",
            name="registration_period",
            field=models.ForeignKey(
                blank=True,
                help_text="Only set a value here if the registration period is "
                "different to the general registration period defined in the offering.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="courses",
                to="courses.registrationperiod",
            ),
        ),
        migrations.AddField(
            model_name="offering",
            name="registration_period",
            field=models.ForeignKey(
                default=default_registration_period,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="offerings",
                to="courses.registrationperiod",
            ),
        ),
    ]
