# Generated by Django 3.2.12 on 2022-03-23 13:18

import courses.models.user_profile
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('courses', '0012_auto_20211027_1712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to=courses.models.user_profile.upload_path),
        ),
    ]
