# Generated by Django 4.2.5 on 2023-09-12 11:46

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0012_registrationperiod_remove_course_active_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="registrationperiod",
            options={"ordering": ["name"]},
        ),
        migrations.AlterField(
            model_name="offering",
            name="registration_period",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="offerings",
                to="courses.registrationperiod",
            ),
        ),
        migrations.AlterField(
            model_name="registrationperiod",
            name="start",
            field=models.DateTimeField(
                default=datetime.date(1970, 1, 1),
                help_text="People will be able to sign up for courses, starting with "
                "this point in time.",
            ),
        ),
    ]
