# Generated by Django 4.2.6 on 2023-10-28 12:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0012_offering_order_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="course",
            options={"ordering": ["offering", "name"]},
        ),
        migrations.RemoveField(
            model_name="course",
            name="position",
        ),
    ]
