# Generated by Django 4.2.6 on 2023-11-06 09:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0013_alter_course_options_remove_course_position"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="course",
            name="evaluated",
        ),
        migrations.AddField(
            model_name="course",
            name="experience_mandatory",
            field=models.BooleanField(
                default=False,
                help_text="If enabled, people registering for this course need to state "
                "their experience.",
            ),
        ),
    ]
