# Generated by Django 3.2.12 on 2022-04-03 21:25

from django.db import migrations, models
import utils.code_generator


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0015_auto_20220403_2158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscribe',
            name='usi',
            field=models.CharField(blank=True,
                                   default=utils.code_generator.CodeGenerator.short_uuid_without_ambiguous_characters,
                                   help_text='Unique subscription identifier: Randomly generated',
                                   max_length=6, unique=True),
        ),
    ]
