# Generated by Django 5.0.3 on 2024-03-16 00:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0016_voucher_comment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='voucher',
            name='sent_to',
            field=models.ForeignKey(blank=True, help_text='User that the voucher was sent to.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='voucher_send_to', to=settings.AUTH_USER_MODEL),
        ),
    ]
