# Generated by Django 5.0.2 on 2024-03-21 21:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0016_alter_userprofile_nationality"),
        ("courses", "0017_voucher_sent_to"),
    ]

    operations = []
