# Generated by Django 3.2.13 on 2022-10-27 20:27

from django.db import migrations, models

def migrate_title(apps, schema_editor) -> None:
    model = apps.get_model('courses', 'CourseType')
    model_translation = apps.get_model('courses', 'CourseTypeTranslation')

    for course_type_instance in model.objects.all():
        for translation in model_translation.objects.filter(master_id=course_type_instance.pk).all():
            translation.title = course_type_instance.name
            translation.save()

class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0017_auto_20220419_1022'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coursetype',
            options={},
        ),
        migrations.AddField(
            model_name='coursetypetranslation',
            name='subtitle',
            field=models.CharField(blank=True, help_text='A short teaser, that is displayed below the title for more information.', max_length=128, null=True, verbose_name='[TR] Subtitle'),
        ),
        migrations.AddField(
            model_name='coursetypetranslation',
            name='title',
            field=models.CharField(default='', help_text='This will be the title shown for all courses of this type.', max_length=64, verbose_name='[TR] Title'),
            preserve_default=False,
        ),
        migrations.RunPython(
            code=migrate_title,
        ),
        migrations.RemoveField(
            model_name='coursetype',
            name='name',
        ),
    ]
