# Generated by Django 4.1.7 on 2023-04-05 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_remove_userprofile_default_hourly_wage_and_more'),
        ('courses', '0018_alter_musicpluginmodel_cmsplugin_ptr'),
    ]

    operations = [
    ]
