# Generated by Django 4.0.8 on 2022-12-14 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0019_alter_musicpluginmodel_cmsplugin_ptr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscribe',
            name='paymentmethod',
            field=models.CharField(blank=True, choices=[('counter', 'counter'), ('course', 'course'), ('online', 'online'), ('voucher', 'voucher'), ('reduction', 'price reduction'), ('manual', 'manual')], max_length=30, null=True),
        ),
    ]
