# Generated by Django 5.0.3 on 2024-04-19 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0019_offering_survey_alter_voucher_sent_to"),
    ]

    operations = [
        migrations.AlterField(
            model_name="voucher",
            name="comment",
            field=models.CharField(
                blank=True,
                help_text="Optional description of the purpose of the voucher.",
                max_length=200,
                null=True,
            ),
        ),
    ]
