# Generated by Django 5.0.3 on 2024-04-22 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0020_alter_voucher_comment"),
        ("courses", "0020_coursetranslation_information_for_participants"),
    ]

    operations = []
