# Generated by Django 5.0.3 on 2024-04-22 11:31

from django.db import migrations
from djangocms_text.fields import HTMLField


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0021_merge_20240422_1329"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="coursetranslation",
            name="information_for_participants",
        ),
        migrations.AddField(
            model_name="coursetranslation",
            name="information_for_participants_teachers",
            field=HTMLField(
                blank=True,
                help_text="Shown only to participants of the course on the course page. Can be set by teachers in the frontend.",
                null=True,
                verbose_name="[TR] Information for participants (editable by teachers)",
            ),
        ),
    ]
