# Generated by Django 5.0.3 on 2024-04-22 11:55

from django.db import migrations
from djangocms_text.fields import HTMLField


class Migration(migrations.Migration):
    dependencies = [
        (
            "courses",
            "0022_remove_coursetranslation_information_for_participants_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="coursetranslation",
            name="information_for_participants_admin",
            field=HTMLField(
                blank=True,
                help_text="Shown only to participants of the course on the course page. Cannot be set by teachers in the frontend.",
                null=True,
                verbose_name="[TR] Information for participants (editable by admins only)",
            ),
        ),
    ]
