# Generated by Django 5.0.3 on 2024-04-22 10:34

from django.db import migrations
from djangocms_text.fields import HTMLField


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0023_coursetranslation_information_for_participants_admin"),
    ]

    operations = [
        migrations.AddField(
            model_name="coursetypetranslation",
            name="information_for_participants",
            field=HTMLField(
                blank=True,
                help_text="Shown only to participants of courses of this type on the course page. Cannot be set by teachers in the frontend.",
                null=True,
                verbose_name="[TR] Information for participants",
            ),
        ),
    ]
