# Generated by Django 5.0.3 on 2024-04-23 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0025_offeringtranslation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="offering",
            name="name",
            field=models.CharField(
                help_text="Identifier of the offering. For internal use.",
                max_length=30,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="offeringtranslation",
            name="title",
            field=models.CharField(
                blank=True,
                help_text="Title of the offering shown to users.",
                max_length=30,
                null=True,
                verbose_name="[TR] Title",
            ),
        ),
    ]
