# Generated by Django 5.0.4 on 2024-05-21 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0027_alter_userprofile_picture"),
    ]

    operations = [
        migrations.AlterField(
            model_name="offeringtranslation",
            name="title",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Title of the offering shown to users.",
                max_length=30,
                verbose_name="[TR] Title",
            ),
            preserve_default=False,
        ),
    ]
