# Generated by Django 5.0.4 on 2024-05-28 13:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0029_alter_offeringtranslation_title"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LessonOccurrence",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start", models.DateTimeField()),
                ("end", models.DateTimeField()),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lesson_occurrences",
                        to="courses.course",
                    ),
                ),
                (
                    "teachers",
                    models.ManyToManyField(
                        related_name="lesson_occurrences", to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
        ),
    ]
