# Generated by Django 5.0.4 on 2024-05-28 14:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0030_lessonoccurrence"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="lessonoccurrence",
            name="teachers",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="lesson_occurrences",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
