# Generated by Django 5.0.4 on 2024-05-28 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0031_alter_lessonoccurrence_teachers"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="lessonoccurrence",
            unique_together={("course", "start", "end")},
        ),
    ]
