# Generated by Django 5.0.6 on 2024-06-04 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0031_lessonoccurrence_create_from_courses"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="teach",
            name="hourly_wage",
        ),
    ]
