# Generated by Django 5.0.6 on 2024-06-16 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0030_remove_teach_hourly_wage_lessonoccurrence_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="completed",
            field=models.BooleanField(
                default=False,
                help_text="If true, will disable teachers presence editing.",
            ),
        ),
    ]
