# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-28 21:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('courses', '0033_auto_20160704_1158'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='language',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='privacy',
        ),
    ]
