# Generated by Django 5.0.6 on 2024-06-17 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0032_course_completed"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subscribe",
            name="state",
            field=models.CharField(
                choices=[
                    ("new", "new"),
                    ("waiting_list", "waiting list"),
                    ("confirmed", "confirmed (to pay)"),
                    ("payed", "paid"),
                    ("completed", "completed"),
                    ("rejected", "rejected"),
                    ("to_reimburse", "to reimburse"),
                ],
                db_index=True,
                max_length=30,
            ),
        ),
    ]
