# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-29 13:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0034_auto_20160828_2324'),
    ]

    operations = [
        migrations.RunSQL(
            r'''ALTER TABLE courses_userprofile DROP COLUMN mugshot;'''
        ),
    ]
