# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-02 09:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import djangocms_text_ckeditor.fields


class Migration(migrations.Migration):
    dependencies = [
        ('courses', '0035_remove_mugshot'),
    ]

    def migrate_untranslated_course(apps, schema_editor):
        MyModel = apps.get_model('courses', 'Course')
        MyModelTranslation = apps.get_model('courses', 'CourseTranslation')

        for object in MyModel.objects.all():
            MyModelTranslation.objects.create(
                master_id=object.pk,
                language_code='de',
                description=object.special,
            )

    def migrate_untranslated_style(apps, schema_editor):
        MyModel = apps.get_model('courses', 'Style')
        MyModelTranslation = apps.get_model('courses', 'StyleTranslation')

        for object in MyModel.objects.all():
            MyModelTranslation.objects.create(
                master_id=object.pk,
                language_code='de',
                description=object.description,
            )

    def migrate_untranslated_room(apps, schema_editor):
        MyModel = apps.get_model('courses', 'Room')
        MyModelTranslation = apps.get_model('courses', 'RoomTranslation')

        for object in MyModel.objects.all():
            MyModelTranslation.objects.create(
                master_id=object.pk,
                language_code='de',
                description=object.description,
            )

    def migrate_untranslated_coursetype(apps, schema_editor):
        MyModel = apps.get_model('courses', 'CourseType')
        MyModelTranslation = apps.get_model('courses', 'CourseTypeTranslation')

        for object in MyModel.objects.all():
            MyModelTranslation.objects.create(
                master_id=object.pk,
                language_code='de',
                description=object.description,
            )

    operations = [
        migrations.CreateModel(
            name='CourseTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('description', djangocms_text_ckeditor.fields.HTMLField(blank=True,
                                                                         help_text='Description specific for this course. (Gets displayed combined with the description of the course style)',
                                                                         null=True)),
            ],
            options={
                'verbose_name': 'course Translation',
                'default_permissions': (),
                'db_tablespace': '',
                'managed': True,
                'db_table': 'courses_course_translation',
            },
        ),
        migrations.CreateModel(
            name='CourseTypeTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('description', djangocms_text_ckeditor.fields.HTMLField(blank=True,
                                                                         help_text='This text is added to the description of each course instance.',
                                                                         null=True)),
            ],
            options={
                'verbose_name': 'course type Translation',
                'default_permissions': (),
                'db_tablespace': '',
                'managed': True,
                'db_table': 'courses_coursetype_translation',
            },
        ),
        migrations.CreateModel(
            name='RoomTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('description', djangocms_text_ckeditor.fields.HTMLField(blank=True, null=True)),
                ('teacher_info', models.TextField(blank=True,
                                                  help_text='Information for the teachers only (e.g. how to prepare the room for courses)',
                                                  null=True)),
            ],
            options={
                'verbose_name': 'room Translation',
                'default_permissions': (),
                'db_tablespace': '',
                'managed': True,
                'db_table': 'courses_room_translation',
            },
        ),
        migrations.CreateModel(
            name='StyleTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('description', djangocms_text_ckeditor.fields.HTMLField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'style Translation',
                'default_permissions': (),
                'db_tablespace': '',
                'managed': True,
                'db_table': 'courses_style_translation',
            },
        ),
        migrations.AddField(
            model_name='styletranslation',
            name='master',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    related_name='translations', to='courses.Style'),
        ),
        migrations.AddField(
            model_name='roomtranslation',
            name='master',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    related_name='translations', to='courses.Room'),
        ),
        migrations.AddField(
            model_name='coursetypetranslation',
            name='master',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    related_name='translations', to='courses.CourseType'),
        ),
        migrations.AddField(
            model_name='coursetranslation',
            name='master',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    related_name='translations', to='courses.Course'),
        ),
        migrations.AlterUniqueTogether(
            name='styletranslation',
            unique_together=set([('language_code', 'master')]),
        ),
        migrations.AlterUniqueTogether(
            name='roomtranslation',
            unique_together=set([('language_code', 'master')]),
        ),
        migrations.AlterUniqueTogether(
            name='coursetypetranslation',
            unique_together=set([('language_code', 'master')]),
        ),
        migrations.AlterUniqueTogether(
            name='coursetranslation',
            unique_together=set([('language_code', 'master')]),
        ),
        migrations.RunPython(migrate_untranslated_style),
        migrations.RunPython(migrate_untranslated_room),
        migrations.RunPython(migrate_untranslated_coursetype),
        migrations.RunPython(migrate_untranslated_course),
        migrations.RemoveField(
            model_name='course',
            name='special',
        ),
        migrations.RemoveField(
            model_name='coursetype',
            name='description',
        ),
        migrations.RemoveField(
            model_name='room',
            name='description',
        ),
        migrations.RemoveField(
            model_name='style',
            name='description',
        ),
    ]
