# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-06 09:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post_office', '0001_initial'),
        ('courses', '0037_auto_20160905_1307'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherWelcome',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True, help_text='The date when the welcome mail was sent to the teacher.')),
                ('mail', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='post_office.Email')),
            ],
        ),
        migrations.AddField(
            model_name='confirmation',
            name='mail',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='post_office.Email'),
        ),
        migrations.AddField(
            model_name='rejection',
            name='mail',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='post_office.Email'),
        ),
        migrations.AddField(
            model_name='teach',
            name='welcomed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='teacherwelcome',
            name='teach',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_welcomes', to='courses.Teach'),
        ),
    ]
