# Generated by Django 5.0.6 on 2024-06-25 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0037_alter_rejection_reason"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="course",
            name="preceding_courses",
        ),
        migrations.AddField(
            model_name="course",
            name="early_signup",
            field=models.BooleanField(
                default=True,
                help_text="Defines if users eligible for early sign-up can subscribe to this course (if checked, course early sign-up is enabled if offering early sign-up is enabled).",
            ),
        ),
        migrations.AddField(
            model_name="coursetype",
            name="predecessors",
            field=models.ManyToManyField(
                blank=True,
                help_text="Course types that allow for early subscription (within time bounds) to courses if this type.",
                null=True,
                related_name="successors",
                to="courses.coursetype",
            ),
        ),
        migrations.AddField(
            model_name="offering",
            name="early_signup",
            field=models.BooleanField(
                default=False,
                help_text="Defines if users eligible for early sign-up can subscribe to courses in this offering.",
            ),
        ),
        migrations.AddField(
            model_name="offering",
            name="early_signup_max_days",
            field=models.PositiveSmallIntegerField(
                default=180,
                help_text="Maximum days between the last lesson of the preceding course and the first one of the succeeding course to be eligible for early sign-up (if applicable)",
                verbose_name="Max days for early sign-up",
            ),
        ),
        migrations.DeleteModel(
            name="CourseSuccession",
        ),
    ]
