# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-27 21:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0038_auto_20160906_1116'),
    ]

    operations = [
        migrations.AddField(
            model_name='voucher',
            name='subscription',
            field=models.ForeignKey(blank=True, help_text='subscription that was paid with this voucher', null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.Subscribe'),
        ),
    ]
