# Generated by Django 5.0.6 on 2024-06-26 08:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "courses",
            "0038_remove_course_preceding_courses_course_early_signup_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="type",
            field=models.ForeignKey(
                help_text="The name of the course type is displayed on the website as the course title.",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="courses",
                to="courses.coursetype",
            ),
        ),
    ]
