# Generated by Django 5.0.7 on 2024-09-08 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0039_alter_course_type"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="lessonoccurrence",
            options={"ordering": ["course", "start"]},
        ),
    ]
