# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-20 20:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0039_voucher_subscription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscribe',
            name='matching_state',
            field=models.CharField(choices=[('unknown', 'Unknown'), ('couple', 'Couple'), ('to_match', 'To match'), ('to_rematch', 'To rematch'), ('matched', 'Matched'), ('not_required', 'Not required')], db_index=True, default='unknown', max_length=30),
        ),
        migrations.AlterField(
            model_name='subscribe',
            name='state',
            field=models.CharField(choices=[('new', 'new'), ('confirmed', 'confirmed (to pay)'), ('payed', 'payed'), ('completed', 'completed'), ('rejected', 'rejected'), ('to_reimburse', 'to reimburse')], db_index=True, default='new', max_length=30),
        ),
    ]
