# Generated by Django 5.0.9 on 2024-10-19 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0040_alter_lessonoccurrence_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="display_name",
            field=models.CharField(
                blank=True,
                help_text="Displayed name. Only available for teachers. If not set, will fall back to full name.",
                max_length=30,
                null=True,
            ),
        ),
    ]
