# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-20 21:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0040_auto_20161120_2139'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscribe',
            name='price_to_pay',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
    ]
