# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-13 09:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0041_subscribe_price_to_pay'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseSuccession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('predecessor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='successing_courses_through', to='courses.Course')),
                ('successor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preceding_courses_through', to='courses.Course')),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='preceding_courses',
            field=models.ManyToManyField(help_text='The course(s) that are immediate predecessors of this course.', related_name='succeeding_courses', through='courses.CourseSuccession', to='courses.Course'),
        ),
    ]
