# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-15 10:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0042_auto_20170413_0935'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iban', models.CharField(help_text='IBAN in the standardized format.', max_length=255)),
                ('bank_name', models.CharField(help_text='Name of the bank.', max_length=255)),
                ('zip_code', models.CharField(help_text='Zipcode of the bank.', max_length=255)),
                ('city', models.CharField(help_text='City of the bank.', max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='address',
            name='country',
            field=django_countries.fields.CountryField(default='CH', max_length=2),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='ahv_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='birthdate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='nationality',
            field=django_countries.fields.CountryField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='residence_permit',
            field=models.CharField(blank=True, choices=[('N', 'Permit N (permit for asylum-seekers)'), ('S', 'Permit S (people in need of protection)'), ('F', 'Permit F (provisionally admitted foreigners)'), ('SWISS', 'Swiss citizen'), ('B', 'B EU/EFTA permit (Resident foreign nationals)'), ('C', 'C EU/EFTA permit (Settled foreign nationals)'), ('G', 'G EU/EFTA permit (Cross-border commuters)'), ('L', 'L EU/EFTA permit (Short-term residents)'), ('Ci', 'Ci EU/EFTA permit (Resident foreign nationals with gainful employment)'), ('<NO>', 'Short-term stay without VISA')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='bank_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.BankAccount'),
        ),
    ]
