# Generated by Django 5.0.9 on 2024-12-18 15:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0042_alter_rejection_reason"),
    ]

    operations = [
        migrations.CreateModel(
            name="RoomCancellation",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        help_text="Recommended. Makes identifying the cancellation easier.",
                        max_length=50,
                        null=True,
                    ),
                ),
                ("date", models.DateField()),
                (
                    "room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cancellations",
                        to="courses.room",
                    ),
                ),
            ],
        ),
    ]
