# Generated by Django 5.0.9 on 2024-12-22 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0043_roomcancellation"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="roomcancellation",
            options={"ordering": ["-date"]},
        ),
    ]
