# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-15 11:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0043_auto_20170415_1059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='residence_permit',
            field=models.CharField(blank=True, choices=[('SWISS', 'Swiss citizen'), ('B', 'B EU/EFTA permit (Resident foreign nationals)'), ('C', 'C EU/EFTA permit (Settled foreign nationals)'), ('Ci', 'Ci EU/EFTA permit (Resident foreign nationals with gainful employment)'), ('L', 'L EU/EFTA permit (Short-term residents)'), ('G', 'G EU/EFTA permit (Cross-border commuters)'), ('F', 'Permit F (provisionally admitted foreigners)'), ('N', 'Permit N (permit for asylum-seekers)'), ('S', 'Permit S (people in need of protection)'), ('<NO>', 'Short-term stay without VISA')], max_length=30, null=True),
        ),
    ]
