# Generated by Django 5.1.6 on 2025-02-08 20:55

import djangocms_text.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0044_alter_roomcancellation_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="roomtranslation",
            name="disclaimer",
            field=models.TextField(
                blank=True,
                help_text="Important notes for this room, that will be shown together "
                "with the course description. E.g. required ASVZ membership, notes on "
                "last minute cancellations for food&lab, etc.",
                null=True,
                verbose_name="[TR] Instructions",
            ),
        ),
        migrations.AddField(
            model_name="roomtranslation",
            name="information_for_participants",
            field=djangocms_text.fields.HTMLField(
                blank=True,
                help_text="Shown only to participants who are confirmed for a course "
                "in this room.",
                null=True,
                verbose_name="[TR] Information for participants",
            ),
        ),
        migrations.AlterField(
            model_name="roomtranslation",
            name="description",
            field=djangocms_text.fields.HTMLField(
                blank=True,
                help_text="Information on how to get to the room. E.g. where it is "
                "located, what entrance to use, or any additional information.",
                null=True,
                verbose_name="[TR] Description",
            ),
        ),
        migrations.AlterField(
            model_name="roomtranslation",
            name="instructions",
            field=models.TextField(
                blank=True,
                help_text="Instructions for teachers/staff. E.g. how to get access, "
                "how to use the sound system, noise regulations, etc.",
                null=True,
                verbose_name="[TR] Disclaimer",
            ),
        ),
    ]
