# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-15 11:18
from __future__ import unicode_literals

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0045_auto_20170415_1116'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankaccount',
            name='bank_country',
            field=django_countries.fields.CountryField(default='CH', max_length=2),
        ),
    ]
