# Generated by Django 5.1.6 on 2025-02-08 21:48

import djangocms_text.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0045_roomtranslation_disclaimer_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="roomtranslation",
            name="disclaimer",
            field=djangocms_text.fields.HTMLField(
                blank=True,
                help_text="Important notes for this room, that will be shown together "
                "with the course description. E.g. required ASVZ membership, notes "
                "on last minute cancellations for food&lab, etc.",
                null=True,
                verbose_name="[TR] Instructions",
            ),
        ),
        migrations.AlterField(
            model_name="roomtranslation",
            name="instructions",
            field=djangocms_text.fields.HTMLField(
                blank=True,
                help_text="Instructions for teachers/staff. E.g. how to get access, "
                "how to use the sound system, noise regulations, etc.",
                null=True,
                verbose_name="[TR] Disclaimer",
            ),
        ),
    ]
