# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-14 07:57
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0047_auto_20170415_1207'),
    ]

    operations = [
        migrations.RenameField(
            model_name='periodcancellation',
            old_name='course',
            new_name='period',
        ),
        migrations.AlterField(
            model_name='course',
            name='offering',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='courses.Offering'),
        ),
        migrations.AlterField(
            model_name='course',
            name='period',
            field=models.ForeignKey(blank=True, help_text='You can set a custom period for this course here. If this is left empty, the period from the offering is taken.', null=True, on_delete=django.db.models.deletion.PROTECT, to='courses.Period'),
        ),
        migrations.AlterField(
            model_name='course',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='courses', to='courses.Room'),
        ),
        migrations.AlterField(
            model_name='course',
            name='type',
            field=models.ForeignKey(help_text='The name of the course type is displayed on the website as the course title .', on_delete=django.db.models.deletion.PROTECT, related_name='courses', to='courses.CourseType'),
        ),
        migrations.AlterField(
            model_name='irregularlesson',
            name='room',
            field=models.ForeignKey(blank=True, help_text='The room for this lesson. If left empty, the course room is assumed.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='irregular_lessons', to='courses.Room'),
        ),
        migrations.AlterField(
            model_name='offering',
            name='period',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='courses.Period'),
        ),
        migrations.AlterField(
            model_name='room',
            name='address',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='courses.Address'),
        ),
        migrations.AlterField(
            model_name='subscribe',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='courses.Course'),
        ),
        migrations.AlterField(
            model_name='subscribe',
            name='partner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions_as_partner', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='subscribe',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='courses.Address'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='bank_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='courses.BankAccount'),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='purpose',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vouchers', to='courses.VoucherPurpose'),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='subscription',
            field=models.ForeignKey(blank=True, help_text='subscription that was paid with this voucher', null=True, on_delete=django.db.models.deletion.PROTECT, to='courses.Subscribe'),
        ),
    ]
