# Generated by Django 5.1.8 on 2025-04-14 15:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

from courses.utils import skill_utils


def initialize_skills(apps, schema_editor) -> None:
    user_model = apps.get_model("auth", "User")
    skill_model = apps.get_model("courses", "Skill")
    for user in user_model.objects.all():
        skill = skill_model.objects.create(user=user)
        skill.unlocked_course_types.set(
            skill_utils.calculate_unlocked_course_types(user)
        )


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0048_remove_song_style_alter_coursetype_predecessors_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Skill",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "unlocked_course_types",
                    models.ManyToManyField(
                        help_text="Course types which this user has unlocked. For "
                        "example, participating Ballroom 5 unlocks Ballroom 1-5. "
                        "This information can be used for checking whether "
                        "prerequisites are met, i.e for participating in an advanced "
                        "course, or substituting for a lesson.",
                        related_name="skills",
                        to="courses.coursetype",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="skills",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Attendance",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("p", "present"),
                            ("absent_excused", "absent, excused"),
                            ("absent_not_excused", "absent, not excused"),
                            ("replacement_confirmed", "replacement confirmed"),
                            ("replacement_pending", "replacement pending"),
                        ],
                        default="p",
                        max_length=24,
                    ),
                ),
                (
                    "lesson_occurrence",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attendances",
                        to="courses.lessonoccurrence",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attendances",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("lesson_occurrence", "user")},
            },
        ),
        migrations.RunPython(initialize_skills),
    ]
