# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-14 09:29
from __future__ import unicode_literals

from django.db import migrations, models
import djangocms_text_ckeditor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0048_auto_20170614_0757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursetranslation',
            name='description',
            field=djangocms_text_ckeditor.fields.HTMLField(blank=True, help_text='Description specific for this course. (Gets displayed combined with the description of the course style)', null=True, verbose_name='[TR] Description'),
        ),
        migrations.AlterField(
            model_name='coursetypetranslation',
            name='description',
            field=djangocms_text_ckeditor.fields.HTMLField(blank=True, help_text='This text is added to the description of each course instance.', null=True, verbose_name='[TR] Description'),
        ),
        migrations.AlterField(
            model_name='roomtranslation',
            name='description',
            field=djangocms_text_ckeditor.fields.HTMLField(blank=True, null=True, verbose_name='[TR] Description'),
        ),
        migrations.AlterField(
            model_name='roomtranslation',
            name='instructions',
            field=models.TextField(blank=True, help_text='Instructions to prepare the room (for teachers/staff only)', null=True, verbose_name='[TR] Instructions'),
        ),
        migrations.AlterField(
            model_name='styletranslation',
            name='description',
            field=djangocms_text_ckeditor.fields.HTMLField(blank=True, null=True, verbose_name='[TR] Description'),
        ),
    ]
