# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-11-03 14:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0049_auto_20170614_0929'),
    ]

    operations = [
        migrations.AddField(
            model_name='teach',
            name='hourly_wage',
            field=models.FloatField(default=30.0, help_text='Hourly wage, by default the wage set in the teachers profile is taken.'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='default_hourly_wage',
            field=models.FloatField(default=30.0, help_text='The default hourly wage, which serves as a preset value for taught courses. '),
        ),
    ]
