# Generated by Django 5.2 on 2025-04-24 19:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0050_alter_skill_user"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="attendance",
            name="state",
            field=models.CharField(
                choices=[
                    ("present", "present"),
                    ("absent_excused", "absent, excused"),
                    ("absent_not_excused", "absent, not excused"),
                    ("replacement_confirmed", "replacement confirmed"),
                    ("replacement_pending", "replacement pending"),
                ],
                default="present",
                max_length=24,
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="subscribers",
            field=models.ManyToManyField(
                related_name="courses",
                through="courses.Subscribe",
                through_fields=("course", "user"),
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
