# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-11-04 11:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0050_auto_20171103_1423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teach',
            name='hourly_wage',
            field=models.FloatField(blank=True, help_text='Hourly wage, leave empty to copy default wage from teacher profile.', null=True),
        ),
    ]
