# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-05-07 17:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0051_auto_20171104_1110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(choices=[('m', 'Man'), ('w', 'Woman')], default=None, max_length=1, null=True),
        ),
    ]
