# Generated by Django 5.2 on 2025-04-27 18:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0051_alter_attendance_state_alter_course_subscribers"),
    ]

    operations = [
        migrations.AddField(
            model_name="attendance",
            name="role",
            field=models.CharField(
                choices=[("l", "lead"), ("f", "follow")],
                default="n",
                max_length=1,
            ),
            preserve_default=False,
        ),
    ]
