# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-06-01 22:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0052_auto_20180507_1705'),
    ]

    operations = [
        migrations.AddField(
            model_name='voucher',
            name='percentage',
            field=models.IntegerField(default=100),
        ),
    ]
