# Generated by Django 5.2.1 on 2025-06-01 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0052_attendance_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="teach",
            name="hourly_wage",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Leave empty (not 0!) to follow TQ standard wage scheme",
                max_digits=6,
                null=True,
            ),
        ),
    ]
