# Generated by Django 5.2.3 on 2025-06-29 16:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0053_teach_hourly_wage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attendance",
            name="state",
            field=models.CharField(
                choices=[
                    ("present", "present"),
                    ("absent_excused", "absent, excused"),
                    ("absent_not_excused", "absent, not excused"),
                    ("replacement", "replacement"),
                ],
                default="present",
                max_length=24,
            ),
        ),
    ]
