# Generated by Django 5.2.2 on 2025-07-20 11:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0053_teach_hourly_wage"),
    ]

    operations = [
        migrations.CreateModel(
            name="SwitchData",
            fields=[
                (
                    "user_profile",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="switch_data",
                        serialize=False,
                        to="courses.userprofile",
                    ),
                ),
                (
                    "swiss_edu_id",
                    models.CharField(
                        help_text="Unique person identifier in the Switch edu-ID federation, institution-agnostic.",
                        max_length=36,
                        unique=True,
                        verbose_name="swissEduID",
                    ),
                ),
                (
                    "swiss_edu_person_unique_id",
                    models.CharField(
                        help_text="Unique person identifier in the Switch edu-ID federation, institution-aware.",
                        max_length=36,
                        unique=True,
                        verbose_name="swissEduPersonUniqueID",
                    ),
                ),
                (
                    "given_name",
                    models.CharField(
                        help_text="Given name or first name of the End-User",
                        max_length=150,
                        verbose_name="givenName",
                    ),
                ),
                (
                    "family_name",
                    models.CharField(
                        help_text="Surname or last name of the End-User",
                        max_length=150,
                        verbose_name="surname",
                    ),
                ),
                (
                    "email",
                    models.CharField(
                        help_text="\tEnd-User's preferred e-mail address",
                        max_length=256,
                        unique=True,
                        verbose_name="email",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="userprofile",
            name="student_validity",
            field=models.DateField(
                blank=True,
                help_text="Last date of validity of student status.",
                null=True,
            ),
        ),
        migrations.CreateModel(
            name="SwitchDataAffiliation",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("affiliation", models.CharField(max_length=256)),
                (
                    "switch_data",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="affiliations",
                        to="courses.switchdata",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SwitchDataAffiliationEmail",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=256)),
                (
                    "switch_data",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="affiliation_emails",
                        to="courses.switchdata",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SwitchDataAssociatedEmail",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=256)),
                (
                    "switch_data",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="associated_emails",
                        to="courses.switchdata",
                    ),
                ),
            ],
        ),
    ]
