# Generated by Django 5.2.3 on 2025-07-01 11:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0054_alter_attendance_state"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="attendance",
            options={"ordering": ["-lesson_occurrence__start", "state", "role"]},
        ),
    ]
