# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-25 17:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0055_auto_20190425_1717'),
    ]

    operations = [
        migrations.RunSQL(
            "DROP TABLE IF EXISTS userena_userenasignup"
        )
    ]
