# Generated by Django 5.2.4 on 2025-07-20 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0054_switchdata_userprofile_student_validity_and_more"),
        ("courses", "0055_alter_attendance_options"),
    ]

    operations = []
