# Generated by Django 5.2.4 on 2025-07-20 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0056_merge_20250720_1640"),
    ]

    operations = [
        migrations.AlterField(
            model_name="switchdata",
            name="email",
            field=models.CharField(
                help_text="\tEnd-User's preferred e-mail address",
                max_length=256,
                unique=True,
                verbose_name="email_verified",
            ),
        ),
        migrations.AlterField(
            model_name="switchdata",
            name="family_name",
            field=models.CharField(
                help_text="Surname or last name of the End-User",
                max_length=150,
                verbose_name="family_name",
            ),
        ),
        migrations.AlterField(
            model_name="switchdata",
            name="given_name",
            field=models.CharField(
                help_text="Given name or first name of the End-User",
                max_length=150,
                verbose_name="given_name",
            ),
        ),
    ]
