# Generated by Django 5.2.4 on 2025-07-29 20:52

import django.db.models.deletion
from django.db import migrations, models


def set_room_for_lessons(apps, schema_editor) -> None:
    lesson_occurrence_model = apps.get_model("courses", "LessonOccurrence")
    for lesson_occurrence in lesson_occurrence_model.objects.prefetch_related(
        "course"
    ).all():
        room_id = lesson_occurrence.course.room_id
        if room_id is not None:
            lesson_occurrence.room_id = room_id
            lesson_occurrence.save()


class Migration(migrations.Migration):
    dependencies = [
        (
            "courses",
            "0057_alter_switchdata_email_alter_switchdata_family_name_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="lessonoccurrence",
            name="room",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="lesson_occurrences",
                to="courses.room",
            ),
            preserve_default=False,
        ),
        migrations.RunPython(set_room_for_lessons),
    ]
