# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-23 09:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0057_unique_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='picture',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
