# Generated by Django 5.2.5 on 2025-08-15 17:40

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0058_lessonoccurrence_room"),
    ]

    operations = [
        migrations.CreateModel(
            name="SkillDanceLevel",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "level",
                    models.IntegerField(
                        validators=[django.core.validators.MinValueValidator(1)]
                    ),
                ),
                (
                    "skill",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dance_levels",
                        to="courses.skill",
                    ),
                ),
                (
                    "style",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_skills",
                        to="courses.style",
                    ),
                ),
            ],
            options={
                "ordering": ("skill", "level", "style"),
                "unique_together": {("skill", "style")},
            },
        ),
    ]
