# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-24 16:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0059_auto_20190523_2245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='bank_account',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.BankAccount'),
        ),
    ]
