# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-25 11:48
from __future__ import unicode_literals

from django.db import migrations, models


def migrate_open_class(apps, _):
    course_model = apps.get_model('courses', 'Course')

    course_model.objects.filter(open_class=True).update(subscription_type='open_class')


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0060_auto_20190524_1856'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='subscription_type',
            field=models.CharField(choices=[
                ('regular', 'Regular (internal, with subscription)'),
                ('open_class', 'Open class (no subscription needed)'),
                ('external', 'External (offered by partner of TQ)')
            ], default='regular', max_length=20),
        ),
        migrations.RunPython(migrate_open_class),
        migrations.AlterField(
            model_name='course',
            name='min_subscribers',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.RemoveField(
            model_name='course',
            name='open_class',
        ),
    ]
