# Generated by Django 5.2.5 on 2025-08-18 15:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0060_alter_skilldancelevel_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="skill",
            options={"ordering": ["user__first_name", "user__last_name"]},
        ),
        migrations.RemoveField(
            model_name="skill",
            name="unlocked_course_types",
        ),
    ]
