# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-06 18:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0061_auto_20190525_1348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='offering',
            field=models.ForeignKey(blank=True, help_text='Not required! Useful for regular courses or summer workshops. Do not use for irrgeular courses (e.g. ASVZ open classes)', null=True, on_delete=django.db.models.deletion.PROTECT, to='courses.Offering'),
        ),
        migrations.AlterField(
            model_name='course',
            name='period',
            field=models.ForeignKey(blank=True, help_text='You can set a custom period for this course here. If this is left empty, the period from the offering is taken. Must be set if no offering associated but has regular lessons.', null=True, on_delete=django.db.models.deletion.PROTECT, to='courses.Period'),
        ),
    ]
