# Generated by Django 5.2.5 on 2025-09-20 18:56

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0061_alter_skill_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="price_with_legi",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=Decimal("40"),
                max_digits=6,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="price_without_legi",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=Decimal("80"),
                max_digits=6,
                null=True,
            ),
        ),
    ]
