# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-07-07 14:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0062_auto_20190606_1802'),
    ]

    operations = [
        migrations.AddField(
            model_name='style',
            name='filter_enabled',
            field=models.BooleanField(default=False, help_text='If set to true, users can filter courses list based on this style'),
        ),
        migrations.AddField(
            model_name='style',
            name='parent_style',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.Style'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='student_status',
            field=models.CharField(choices=[('eth', 'ETH'), ('uni', 'UZH'), ('ph', 'PH'), ('other', 'Other'), ('no', 'Not a student')], default='no', max_length=10),
        ),
    ]
