# Generated by Django 6.0.1 on 2026-01-25 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0063_alter_userprofile_nationality'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='personal_data_sharing',
            field=models.BooleanField(default=True, help_text='If True, the user agrees to share personal data with the partner in couple courses.'),
            preserve_default=False,
        ),
    ]
