# Generated by Django 6.0.1 on 2026-01-25 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0063_alter_userprofile_nationality'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teach',
            name='welcomed',
        ),
    ]
