# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-07-07 17:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0063_auto_20190707_1622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='style',
            name='parent_style',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='courses.Style'),
        ),
    ]
