# Generated by Django 6.0.1 on 2026-01-25 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0064_userprofile_personal_data_sharing'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscribe',
            name='personal_data_sharing',
            field=models.BooleanField(default=True, help_text='If True, the subscriber agreed to share personal data at the time of this subscription.'),
            preserve_default=False,
        ),
    ]
