# Generated by Django 6.0.1 on 2026-01-25 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0064_remove_teach_welcomed'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='couples_only',
            field=models.BooleanField(default=False, help_text='If enabled, users may only sign up with a partner.'),
        ),
    ]
