# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-07-07 17:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0064_auto_20190707_1923'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='style',
            options={'ordering': ['name']},
        ),
    ]
