# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-07-07 18:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0065_auto_20190707_1946'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='external_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
