# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-07-12 20:20
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0066_course_external_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='LessonDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lessons', to='courses.Room')),
            ],
        ),
        migrations.CreateModel(
            name='TeachLesson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('welcomed', models.BooleanField(default=False)),
                ('hourly_wage', models.FloatField(blank=True, help_text='Hourly wage, leave empty to copy default wage from teacher profile.', null=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teaching', to='courses.LessonDetails')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teaching_lessons', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='regularlessoncancellation',
            name='course',
        ),
        migrations.RemoveField(
            model_name='course',
            name='teachers',
        ),
        migrations.RemoveField(
            model_name='irregularlesson',
            name='room',
        ),
        migrations.AddField(
            model_name='period',
            name='name',
            field=models.CharField(blank=True, help_text='Recommended. Makes identifying the period easier', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='periodcancellation',
            name='name',
            field=models.CharField(blank=True, help_text='Recommended. Makes identifying the cancellation easier. E.g. Monday after Easter', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='periodcancellation',
            name='date',
            field=models.DateField(default=datetime.datetime(2019, 7, 12, 22, 20, 24, 27789)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='teach',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teaching_courses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='RegularLessonCancellation',
        ),
        migrations.AddField(
            model_name='irregularlesson',
            name='lesson_details',
            field=models.OneToOneField(blank=True, help_text='Only needed, if details are different from course. E.g. different room, different teachers,...', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='irregular_lesson', to='courses.LessonDetails'),
        ),
    ]
