# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-07-12 20:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0067_auto_20190712_2220'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegularLessonException',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='Date of the exception', null=True)),
                ('is_cancellation', models.BooleanField(default=False, help_text='Cancellation of the regular lesson on the given date. No other fields need to be specified.')),
                ('time_from', models.TimeField(blank=True, help_text='Only set, if different', null=True)),
                ('time_to', models.TimeField(blank=True, help_text='Only set, if different', null=True)),
                ('lesson_details', models.OneToOneField(blank=True, help_text='Only needed, if details are different from course. E.g. different room, different teachers,...', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='regular_lesson_exception', to='courses.LessonDetails')),
                ('regular_lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exceptions', to='courses.RegularLesson')),
            ],
            options={
                'ordering': ['date'],
            },
        ),
    ]
