# Generated by Django 6.0.1 on 2026-02-01 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0067_roomaccesscode_roomaccesscode_valid_until_gte_valid_from'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='partner_required_at_signup',
            field=models.BooleanField(default=False, help_text='If enabled, users may only sign up with a partner.'),
        ),
    ]
