# Generated by Django 6.0.2 on 2026-02-22 19:14

import django.db.models.deletion
from django.db import migrations, models


def copy_addresses(apps, schema_editor):
    Room = apps.get_model("courses", "Room")
    UserProfile = apps.get_model("courses", "UserProfile")
    from django.db.models import F

    # Copy address foreign key id into the new FK field
    Room.objects.all().update(address_new_id=F("address_id"))
    UserProfile.objects.all().update(address_new_id=F("address_id"))


def revert_copy_addresses(apps, schema_editor):
    Room = apps.get_model("courses", "Room")
    UserProfile = apps.get_model("courses", "UserProfile")

    # On reverse, clear the new field
    Room.objects.all().update(address_new=None)
    UserProfile.objects.all().update(address_new=None)


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0068_course_partner_required_at_signup'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'verbose_name_plural': 'Addresses'},
        ),
        migrations.AddField(
            model_name='room',
            name='address_new',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='rooms', to='courses.address'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='address_new',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='user_profiles', to='courses.address'),
        ),
        migrations.RunPython(copy_addresses, revert_copy_addresses),
    ]
