# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2019-09-04 15:52
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.deletion
import parler.fields


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0069_remove_teachlesson_welcomed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursetranslation',
            name='master',
            field=parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='courses.Course'),
        ),
        migrations.AlterField(
            model_name='coursetypetranslation',
            name='master',
            field=parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='courses.CourseType'),
        ),
        migrations.AlterField(
            model_name='roomtranslation',
            name='master',
            field=parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='courses.Room'),
        ),
        migrations.AlterField(
            model_name='styletranslation',
            name='master',
            field=parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='courses.Style'),
        ),
    ]
