# Generated by Django 6.0.2 on 2026-02-22 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0069_alter_address_options_room_address_new_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='address',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='address',
        ),
    ]
