# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2019-09-10 15:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0070_auto_20190904_1552'),
    ]

    operations = [
        migrations.AddField(
            model_name='offering',
            name='preview',
            field=models.BooleanField(default=False, help_text='Defines if the offering should be displayed as preview'),
        ),
    ]
