# Generated by Django 6.0.6 on 2026-06-19 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0074_alter_userprofile_personal_data_sharing"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="coursetranslation",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="coursetypetranslation",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="offeringtranslation",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="roomtranslation",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="styletranslation",
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name="coursetranslation",
            constraint=models.UniqueConstraint(
                fields=("language_code", "master"),
                name="courses_course_translation_uniq_lang",
            ),
        ),
        migrations.AddConstraint(
            model_name="coursetypetranslation",
            constraint=models.UniqueConstraint(
                fields=("language_code", "master"),
                name="courses_coursetype_translation_uniq_lang",
            ),
        ),
        migrations.AddConstraint(
            model_name="offeringtranslation",
            constraint=models.UniqueConstraint(
                fields=("language_code", "master"),
                name="courses_offering_translation_uniq_lang",
            ),
        ),
        migrations.AddConstraint(
            model_name="roomtranslation",
            constraint=models.UniqueConstraint(
                fields=("language_code", "master"),
                name="courses_room_translation_uniq_lang",
            ),
        ),
        migrations.AddConstraint(
            model_name="styletranslation",
            constraint=models.UniqueConstraint(
                fields=("language_code", "master"),
                name="courses_style_translation_uniq_lang",
            ),
        ),
    ]
