# Generated by Django 6.0.6 on 2026-06-27 08:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0076_move_opens_soon_to_course"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="payrexx_enabled",
            field=models.BooleanField(
                default=False,
                help_text="If enabled, participants can pay for this course via Payrexx (TWINT or card).",
            ),
        ),
        migrations.AlterField(
            model_name="subscribe",
            name="paymentmethod",
            field=models.CharField(
                blank=True,
                choices=[
                    ("counter", "counter"),
                    ("course", "course"),
                    ("online", "online"),
                    ("voucher", "voucher"),
                    ("reduction", "price reduction"),
                    ("manual", "manual"),
                    ("card", "card (Payrexx)"),
                    ("twint", "TWINT (Payrexx)"),
                ],
                max_length=30,
                null=True,
            ),
        ),
    ]
