# Generated by Django 6.0.6 on 2026-06-27 12:04

import datetime

from django.conf import settings
from django.db import migrations, models

import courses.models.voucher


def convert_percentage_vouchers(apps, schema_editor):
    import reversion

    Voucher = apps.get_model("courses", "Voucher")

    # Used percentage vouchers: set CHF amount from subscription's stored price.
    for voucher in Voucher.objects.filter(
        percentage__isnull=False, amount__isnull=True, used=True
    ).select_related("subscription"):
        if voucher.subscription and voucher.subscription.price_to_pay:
            amount = round(voucher.percentage * voucher.subscription.price_to_pay / 100)
        else:
            amount = 0
        expires = voucher.issued.replace(year=voucher.issued.year + 5)
        with reversion.create_revision():
            voucher.amount = amount
            voucher.expires = expires
            voucher.save()
            reversion.set_comment(
                f"Migrated from {voucher.percentage}% percentage voucher "
                f"to {amount} CHF fixed amount."
            )

    # Unused percentage vouchers issued before 2025: delete.
    Voucher.objects.filter(
        percentage__isnull=False,
        amount__isnull=True,
        used=False,
        issued__lt=datetime.date(2025, 1, 1),
    ).delete()

    # Unused percentage vouchers issued 2025+: assign CHF 40.
    for voucher in Voucher.objects.filter(
        percentage__isnull=False, amount__isnull=True, used=False
    ):
        expires = voucher.issued.replace(year=voucher.issued.year + 5)
        with reversion.create_revision():
            voucher.amount = 40
            voucher.expires = expires
            voucher.save()
            reversion.set_comment(
                f"Migrated from {voucher.percentage}% percentage voucher "
                f"to 40 CHF fixed amount (unused voucher fallback)."
            )


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0076_move_opens_soon_to_course"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="voucher",
            name="percentage is null or between 0 and 100",
        ),
        migrations.RemoveConstraint(
            model_name="voucher",
            name="amount is null or non-negative",
        ),
        migrations.RemoveConstraint(
            model_name="voucher",
            name="either amount or percentage set (not both",
        ),
        migrations.AlterField(
            model_name="voucher",
            name="expires",
            field=models.DateField(
                blank=True,
                default=courses.models.voucher.default_expiry,
                help_text="If not set, the voucher will not expire.",
                null=True,
            ),
        ),
        migrations.RunPython(convert_percentage_vouchers, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name="voucher",
            constraint=models.CheckConstraint(
                condition=models.Q(("amount__isnull", False), ("amount__gt", 0)),
                name="amount is non-null and positive",
            ),
        ),
        migrations.RemoveField(
            model_name="voucher",
            name="percentage",
        ),
    ]
