# Generated by Django 6.0.6 on 2026-06-29 21:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0077_course_payrexx_enabled_alter_subscribe_paymentmethod"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="lessonoccurrenceteach",
            options={"verbose_name_plural": "lesson occurrence teaches"},
        ),
        migrations.AlterModelOptions(
            name="switchdata",
            options={"verbose_name_plural": "switch data"},
        ),
        migrations.AlterModelOptions(
            name="teach",
            options={"verbose_name_plural": "teaches"},
        ),
    ]
