# Generated by Django 6.0.6 on 2026-06-27 15:53

from django.db import migrations, models


def rename_teachers_to_responsible(apps, schema_editor):
    RoomAccessCode = apps.get_model("courses", "RoomAccessCode")
    RoomAccessCode.objects.filter(visibility="teachers").update(
        visibility="responsible"
    )


def rename_responsible_to_teachers(apps, schema_editor):
    RoomAccessCode = apps.get_model("courses", "RoomAccessCode")
    RoomAccessCode.objects.filter(visibility="responsible").update(
        visibility="teachers"
    )


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0082_roomaccesscodeview"),
    ]

    operations = [
        migrations.RunPython(
            rename_teachers_to_responsible,
            reverse_code=rename_responsible_to_teachers,
        ),
        migrations.AlterField(
            model_name="roomaccesscode",
            name="visibility",
            field=models.CharField(
                choices=[
                    ("public", "Public"),
                    ("participants", "Participants"),
                    ("responsible", "People responsible for course/event"),
                    ("staff", "Staff"),
                ],
                max_length=12,
            ),
        ),
    ]
