# Generated by Django 6.0.6 on 2026-06-28 20:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0083_rename_visibility_teachers_to_teachers_djs"),
    ]

    operations = [
        migrations.AlterField(
            model_name="room",
            name="name",
            field=models.CharField(max_length=128, unique=True),
        ),
        migrations.AlterField(
            model_name="roomaccesscode",
            name="visibility",
            field=models.CharField(
                choices=[
                    ("public", "Public"),
                    ("participants", "Participants"),
                    (
                        "responsible",
                        "People responsible (teachers, DJs, organizers,...)",
                    ),
                    ("staff", "Staff"),
                ],
                max_length=12,
            ),
        ),
    ]
