# Generated by Django 6.0.6 on 2026-06-29 22:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0084_alter_room_name_alter_roomaccesscode_visibility"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="roomaccesscode",
            options={
                "verbose_name": "room access code",
                "verbose_name_plural": "room access codes",
            },
        ),
        migrations.AlterModelOptions(
            name="roomaccesscodeview",
            options={
                "ordering": ["-viewed_at"],
                "verbose_name": "room access code view",
                "verbose_name_plural": "room access code views",
            },
        ),
    ]
