# Generated by Django 6.0.7 on 2026-10-03 08:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0085_alter_roomaccesscode_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="switchdata",
            name="swiss_edu_person_unique_id",
            field=models.CharField(
                help_text="Unique person identifier in the Switch edu-ID federation, institution-aware.",
                max_length=255,
                unique=True,
                verbose_name="swissEduPersonUniqueID",
            ),
        ),
    ]
