# Generated by Django 2.2 on 2020-02-15 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms_plugins', '0001_squashed_0008_upcomingeventsandcoursespluginmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thumbnailpluginmodel',
            name='crop',
            field=models.BooleanField(blank=True, default=False, help_text='If this thumbnail should be cropped to fit given size.'),
        ),
        migrations.AlterField(
            model_name='thumbnailpluginmodel',
            name='image',
            field=models.ImageField(blank=True, help_text='Image to show thumbnail for.', null=True, upload_to=''),
        ),
    ]
