# Generated by Django 2.2.12 on 2020-04-29 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0022_auto_20180620_1551'),
        ('cms_plugins', '0002_auto_20200215_1336'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ThumbnailPluginModel',
        ),
    ]
