# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-05 11:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms_plugins', '0002_thumbnailpluginmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagetitlepluginmodel',
            name='cmsplugin_ptr',
            field=models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='cms_plugins_pagetitlepluginmodel', serialize=False, to='cms.CMSPlugin'),
        ),
        migrations.AlterField(
            model_name='thumbnailpluginmodel',
            name='cmsplugin_ptr',
            field=models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='cms_plugins_thumbnailpluginmodel', serialize=False, to='cms.CMSPlugin'),
        ),
    ]
