# Generated by Django 5.1.5 on 2025-01-28 19:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("cms_plugins", "0002_squashed"),
    ]

    operations = [
        migrations.DeleteModel(
            name="CountdownPluginModel",
        ),
    ]
