# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-03 19:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms_plugins', '0003_auto_20160905_1307'),
    ]

    operations = [
        migrations.AddField(
            model_name='thumbnailpluginmodel',
            name='crop',
            field=models.BooleanField(default=False, help_text='If this thumbnail should be cropped to fit given size.'),
        ),
        migrations.AddField(
            model_name='thumbnailpluginmodel',
            name='url',
            field=models.URLField(blank=True, help_text='URL to display on image click.', max_length=500, null=True),
        ),
    ]
