# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-09 09:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0016_auto_20160608_1535'),
        ('cms_plugins', '0004_auto_20170203_1940'),
    ]

    operations = [
        migrations.CreateModel(
            name='CountdownPluginModel',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='cms_plugins_countdownpluginmodel', serialize=False, to='cms.CMSPlugin')),
                ('finish_datetime', models.DateTimeField(help_text='Countdown finish date and time.')),
                ('hide', models.BooleanField(default=True, help_text='Hide Countdown after finished.')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
    ]
