# Generated by Django 3.0.6 on 2020-06-08 19:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0022_auto_20180620_1551'),
        ('cms_plugins', '0004_alertpluginmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuickLinksPluginModel',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='cms_plugins_quicklinkspluginmodel', serialize=False, to='cms.CMSPlugin')),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('text', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='RowPluginModel',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='cms_plugins_rowpluginmodel', serialize=False, to='cms.CMSPlugin')),
                ('column_classes', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
    ]
