# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-09 09:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms_plugins', '0005_countdownpluginmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='countdownpluginmodel',
            name='text',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
    ]
