# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-09 10:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms_plugins', '0006_countdownpluginmodel_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='countdownpluginmodel',
            name='finish_text',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
