# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-07-28 10:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0016_auto_20160608_1535'),
        ('cms_plugins', '0007_countdownpluginmodel_finish_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='UpcomingEventsAndCoursesPluginModel',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='cms_plugins_upcomingeventsandcoursespluginmodel', serialize=False, to='cms.CMSPlugin')),
                ('delta_days', models.IntegerField(blank=True, help_text='Events and courses within the time delta (in days) from now on are shown.Leave empty to make no restrictions.', null=True)),
                ('max_displayed', models.IntegerField(blank=True, help_text='Maximum number of items to be displayed. Leave empty to make no restrictions.', null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
    ]
