# Generated by Django 4.1.5 on 2023-02-19 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0002_squashed'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='hide_from_public_reviews',
            field=models.BooleanField(default=False, help_text='If true, this answer will not be shown publicly.'),
        ),
        migrations.AddField(
            model_name='question',
            name='public_review',
            field=models.BooleanField(default=False, help_text='If true, answers to this question may be displayed publicly'),
        ),
    ]
