# Generated by Django 5.0.3 on 2024-04-17 07:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("survey", "0003_answer_hide_from_public_reviews_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="surveyinstance",
            name="invitation_sent",
        ),
    ]
