# Generated by Django 3.2.12 on 2022-03-25 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0003_auto_20200326_1309'),
    ]

    operations = [
        migrations.AddField(
            model_name='questiongrouptranslation',
            name='title',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='[TR] Title'),
        ),
        migrations.AlterField(
            model_name='surveyinstance',
            name='last_update',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
