# Generated by Django 3.2.12 on 2022-03-25 21:18
import shortuuid
from django.db import migrations, models
from django.db.models import PROTECT


def create_uuid(apps, schema_editor) -> None:
    for survey_instance in apps.get_model('survey', 'surveyinstance').objects.all():
        survey_instance.url_key = shortuuid.uuid()
        survey_instance.save()


def copy_label_to_value(apps, schema_editor) -> None:
    translations = apps.get_model('survey', 'choiceTranslation')
    for choice in apps.get_model('survey', 'choice').objects.all():
        choice.value = translations.objects.filter(master_id=choice.id).first().label[:32]
        choice.save()


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0004_auto_20220325_2019'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ScaleTemplateTranslation',
            new_name='ScaleTranslation',
        ),
        migrations.RenameField(
            model_name='answer',
            old_name='text',
            new_name='value',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='choice',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='scale_template',
            new_name='scale'
        ),
        migrations.AddField(
            model_name='surveytranslation',
            name='title',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='[TR] Title'),
        ),
        migrations.RenameModel(
            old_name='ScaleTemplate',
            new_name='Scale',
        ),
        migrations.AlterModelOptions(
            name='scaletranslation',
            options={'default_permissions': (), 'managed': True, 'verbose_name': 'scale Translation'},
        ),
        migrations.RemoveField(
            model_name='scaletranslation',
            name='mid',
        ),
        migrations.AlterField(
            model_name='question',
            name='scale',
            field=models.ForeignKey(blank=True, help_text='Only needed for question type "choice"', null=True, on_delete=PROTECT, to='survey.scale'),
        ),
        migrations.AlterModelTable(
            name='scaletranslation',
            table='survey_scale_translation',
        ),
        migrations.AddField(
            model_name='surveyinstance',
            name='url_key',
            field=models.CharField(blank=True, null=True, max_length=32),
        ),
        migrations.RunPython(create_uuid),
        migrations.AlterField(
            model_name='surveyinstance',
            name='url_key',
            field=models.CharField(max_length=32, default=shortuuid.uuid, blank=False, null=False, unique=True)
        ),
        migrations.AddField(
            model_name='choice',
            name='value',
            field=models.CharField(default='<none>', max_length=32),
            preserve_default=False,
        ),
        migrations.RunPython(copy_label_to_value),
    ]
