# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-04 09:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0005_auto_20160524_1205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='position',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Position'),
        ),
        migrations.AlterField(
            model_name='question',
            name='display',
            field=models.BooleanField(default=True, help_text='Defines if this question is displayed in survey; set this to false instead of deleting'),
        ),
        migrations.AlterField(
            model_name='question',
            name='position',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Position'),
        ),
        migrations.AlterField(
            model_name='question',
            name='type',
            field=models.CharField(choices=[('c', 'single choice'), ('cf', 'single choice with free form'), ('m', 'multiple choice'), ('mf', 'multiple choice with free form'), ('s', 'scale'), ('f', 'free form')], default='f', max_length=3),
        ),
        migrations.AlterField(
            model_name='questiongroup',
            name='position',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Position'),
        ),
    ]
