# Generated by Django 3.2.12 on 2022-03-26 23:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0005_auto_20220325_2218'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='questiongroup',
            options={'ordering': ['survey__name', 'position']},
        ),
        migrations.AlterField(
            model_name='question',
            name='scale',
            field=models.ForeignKey(blank=True, help_text='Only needed for question type "scale"', null=True, on_delete=django.db.models.deletion.PROTECT, to='survey.scale'),
        ),
    ]
