# Generated by Django 5.0.9 on 2024-11-24 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("survey", "0006_alter_surveyinstance_url_expire_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="surveyinstance",
            name="url_expire_date",
            field=models.DateTimeField(
                help_text="If left empty, will default to 90 days after creation."
            ),
        ),
    ]
