# Generated by Django 3.2.12 on 2022-03-29 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0006_auto_20220327_0018'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveyinstance',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
    ]
