# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-29 12:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0006_auto_20160704_1158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questiongroup',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name='questiongroup',
            unique_together=set([('name', 'survey')]),
        ),
    ]
