# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-29 12:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0007_auto_20161129_1315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name='question',
            unique_together=set([('name', 'question_group')]),
        ),
    ]
