# Generated by Django 6.0.6 on 2026-06-19 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("survey", "0007_alter_surveyinstance_url_expire_date"),
    ]

    operations = [
        # All 5 survey translation tables have plain indexes (not constraints) from DB dump origin.
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql='DROP INDEX IF EXISTS "idx_100813_survey_choice_translation_language_code_41e981649f8c"',
                    reverse_sql=migrations.RunSQL.noop,
                ),
                migrations.RunSQL(
                    sql='DROP INDEX IF EXISTS "idx_100828_survey_questiongroup_transla_language_code_75a0dd454"',
                    reverse_sql=migrations.RunSQL.noop,
                ),
                migrations.RunSQL(
                    sql='DROP INDEX IF EXISTS "idx_100819_survey_question_translation_language_code_1c2871bcdc"',
                    reverse_sql=migrations.RunSQL.noop,
                ),
                migrations.RunSQL(
                    sql='DROP INDEX IF EXISTS "idx_100837_survey_scaletemplate_transla_language_code_4b599f73f"',
                    reverse_sql=migrations.RunSQL.noop,
                ),
                migrations.RunSQL(
                    sql='DROP INDEX IF EXISTS "idx_100843_survey_survey_translation_language_code_70b7fef2116b"',
                    reverse_sql=migrations.RunSQL.noop,
                ),
            ],
            state_operations=[
                migrations.AlterUniqueTogether(
                    name="choicetranslation",
                    unique_together=set(),
                ),
                migrations.AlterUniqueTogether(
                    name="questiongrouptranslation",
                    unique_together=set(),
                ),
                migrations.AlterUniqueTogether(
                    name="questiontranslation",
                    unique_together=set(),
                ),
                migrations.AlterUniqueTogether(
                    name="scaletranslation",
                    unique_together=set(),
                ),
                migrations.AlterUniqueTogether(
                    name="surveytranslation",
                    unique_together=set(),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="choicetranslation",
            constraint=models.UniqueConstraint(
                fields=("language_code", "master"),
                name="survey_choice_translation_uniq_lang",
            ),
        ),
        migrations.AddConstraint(
            model_name="questiongrouptranslation",
            constraint=models.UniqueConstraint(
                fields=("language_code", "master"),
                name="survey_questiongroup_translation_uniq_lang",
            ),
        ),
        migrations.AddConstraint(
            model_name="questiontranslation",
            constraint=models.UniqueConstraint(
                fields=("language_code", "master"),
                name="survey_question_translation_uniq_lang",
            ),
        ),
        migrations.AddConstraint(
            model_name="scaletranslation",
            constraint=models.UniqueConstraint(
                fields=("language_code", "master"),
                name="survey_scale_translation_uniq_lang",
            ),
        ),
        migrations.AddConstraint(
            model_name="surveytranslation",
            constraint=models.UniqueConstraint(
                fields=("language_code", "master"),
                name="survey_survey_translation_uniq_lang",
            ),
        ),
    ]
