# Generated by Django 3.2.12 on 2022-04-06 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0008_alter_surveyinstance_url_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='teachers_allowed',
            field=models.BooleanField(default=False, help_text='If set to true, teachers will be able to view the answers for their courses.'),
        ),
    ]
