# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-14 07:57
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0008_auto_20161129_1319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='choice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='survey.Choice'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='answers', to='survey.Question'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='survey.QuestionGroup'),
        ),
        migrations.AlterField(
            model_name='question',
            name='scale_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='survey.ScaleTemplate'),
        ),
        migrations.AlterField(
            model_name='questiongroup',
            name='survey',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='survey.Survey'),
        ),
        migrations.AlterField(
            model_name='surveyinstance',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='survey_instances', to='courses.Course'),
        ),
        migrations.AlterField(
            model_name='surveyinstance',
            name='survey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='survey_instances', to='survey.Survey'),
        ),
        migrations.AlterField(
            model_name='surveyinstance',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='survey_instances', to=settings.AUTH_USER_MODEL),
        ),
    ]
