# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-14 09:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0009_auto_20170614_0757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choicetranslation',
            name='label',
            field=models.CharField(max_length=255, verbose_name='[TR] Label'),
        ),
        migrations.AlterField(
            model_name='questiongrouptranslation',
            name='intro_text',
            field=models.TextField(blank=True, null=True, verbose_name='[TR] Intro text'),
        ),
        migrations.AlterField(
            model_name='questiontranslation',
            name='note',
            field=models.TextField(blank=True, null=True, verbose_name='[TR] Note'),
        ),
        migrations.AlterField(
            model_name='questiontranslation',
            name='text',
            field=models.TextField(blank=True, null=True, verbose_name='[TR] Text'),
        ),
        migrations.AlterField(
            model_name='scaletemplatetranslation',
            name='low',
            field=models.CharField(max_length=30, verbose_name='[TR] Text for lower'),
        ),
        migrations.AlterField(
            model_name='scaletemplatetranslation',
            name='mid',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='[TR] Text for mid-level'),
        ),
        migrations.AlterField(
            model_name='scaletemplatetranslation',
            name='up',
            field=models.CharField(max_length=30, verbose_name='[TR] Text for upper'),
        ),
        migrations.AlterField(
            model_name='surveytranslation',
            name='intro_text',
            field=models.TextField(blank=True, null=True, verbose_name='[TR] Intro text'),
        ),
    ]
