# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2019-09-04 15:52
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.deletion
import parler.fields


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0010_auto_20170614_0929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choicetranslation',
            name='master',
            field=parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='survey.Choice'),
        ),
        migrations.AlterField(
            model_name='questiongrouptranslation',
            name='master',
            field=parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='survey.QuestionGroup'),
        ),
        migrations.AlterField(
            model_name='questiontranslation',
            name='master',
            field=parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='survey.Question'),
        ),
        migrations.AlterField(
            model_name='scaletemplatetranslation',
            name='master',
            field=parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='survey.ScaleTemplate'),
        ),
        migrations.AlterField(
            model_name='surveytranslation',
            name='master',
            field=parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='survey.Survey'),
        ),
    ]
