# Generated by Django 6.0.7 on 2026-10-06 13:39

import django.db.models.deletion
from django.db import migrations, models

import url_shortener.models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Destination",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("url", models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name="Source",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="ShortLink",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.CharField(blank=True, max_length=255)),
                (
                    "tag",
                    models.CharField(
                        default=url_shortener.models.generate_short_tag,
                        editable=False,
                        max_length=16,
                        unique=True,
                    ),
                ),
                (
                    "deactivated",
                    models.BooleanField(
                        default=False, verbose_name="Manually deactivated"
                    ),
                ),
                ("valid_from", models.DateTimeField(blank=True, null=True)),
                ("valid_until", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "destination",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="short_links",
                        to="url_shortener.destination",
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="short_links",
                        to="url_shortener.source",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Visit",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("visited_at", models.DateTimeField(auto_now_add=True)),
                (
                    "short_link",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="visits",
                        to="url_shortener.shortlink",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["visited_at"], name="url_shorten_visited_e1e4f8_idx"
                    ),
                    models.Index(
                        fields=["short_link", "visited_at"],
                        name="url_shorten_short_l_981068_idx",
                    ),
                ],
            },
        ),
    ]
