# Generated by Django 6.0.7 on 2026-10-02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("url_shortener", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="visit",
            name="ip_address",
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="visit",
            name="user_agent",
            field=models.TextField(blank=True, default=""),
        ),
    ]
