# Generated by Django 6.0.7 on 2026-10-02

import django.db.models.deletion
import url_shortener.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("url_shortener", "0002_visit_ip_address_visit_user_agent"),
    ]

    operations = [
        migrations.CreateModel(
            name="ShortLink",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tag",
                    models.CharField(
                        default=url_shortener.models.generate_short_tag,
                        editable=False,
                        max_length=16,
                        unique=True,
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "destination",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="short_links",
                        to="url_shortener.destination",
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="short_links",
                        to="url_shortener.source",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="visit",
            name="short_link",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="visits",
                to="url_shortener.shortlink",
            ),
        ),
    ]
