# Generated by Django 6.0.7 on 2026-10-02

from django.db import migrations, models


def backfill_short_links(apps, schema_editor):
    ShortLink = apps.get_model("url_shortener", "ShortLink")
    Visit = apps.get_model("url_shortener", "Visit")

    for visit in Visit.objects.filter(short_link__isnull=True).iterator():
        short_link = ShortLink.objects.filter(
            source_id=visit.source_id, destination_id=visit.destination_id
        ).first()
        if short_link is None:
            short_link = ShortLink.objects.create(
                source_id=visit.source_id, destination_id=visit.destination_id
            )
        visit.short_link_id = short_link.id
        visit.save(update_fields=["short_link"])


def restore_source_and_destination(apps, schema_editor):
    Visit = apps.get_model("url_shortener", "Visit")

    for visit in Visit.objects.select_related("short_link").iterator():
        visit.source_id = visit.short_link.source_id
        visit.destination_id = visit.short_link.destination_id
        visit.save(update_fields=["source", "destination"])


class Migration(migrations.Migration):
    dependencies = [
        ("url_shortener", "0003_shortlink_visit_short_link"),
    ]

    operations = [
        migrations.RunPython(backfill_short_links, restore_source_and_destination),
        migrations.AlterField(
            model_name="visit",
            name="short_link",
            field=models.ForeignKey(
                on_delete=models.PROTECT,
                related_name="visits",
                to="url_shortener.shortlink",
            ),
        ),
        migrations.RemoveField(
            model_name="visit",
            name="source",
        ),
        migrations.RemoveField(
            model_name="visit",
            name="destination",
        ),
    ]
