# Generated by Django 6.0.7 on 2026-10-03 08:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("url_shortener", "0004_remove_visit_source_and_destination"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="visit",
            name="url_shorte_source__4d09d0_idx",
        ),
        migrations.AddField(
            model_name="visit",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="url_shortener_visits",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.RemoveField(
            model_name="visit",
            name="ip_address",
        ),
        migrations.RemoveField(
            model_name="visit",
            name="user_agent",
        ),
    ]
