# Generated by Django 6.0.7 on 2026-10-03 09:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("url_shortener", "0005_remove_visit_url_shorte_source__4d09d0_idx_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="shortlink",
            name="description",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
