# Generated by Django 6.0.7 on 2026-10-03

from django.db import migrations, models


def invert_deactivation_state(apps, schema_editor):
    ShortLink = apps.get_model("url_shortener", "ShortLink")
    ShortLink.objects.update(
        deactivated=models.Case(
            models.When(deactivated=True, then=models.Value(False)),
            default=models.Value(True),
            output_field=models.BooleanField(),
        )
    )


class Migration(migrations.Migration):
    dependencies = [
        ("url_shortener", "0006_shortlink_description"),
    ]

    operations = [
        migrations.RenameField(
            model_name="shortlink",
            old_name="active",
            new_name="deactivated",
        ),
        migrations.RunPython(invert_deactivation_state, invert_deactivation_state),
        migrations.AlterField(
            model_name="shortlink",
            name="deactivated",
            field=models.BooleanField(
                default=False, verbose_name="Manually deactivated"
            ),
        ),
        migrations.AddField(
            model_name="shortlink",
            name="valid_from",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="shortlink",
            name="valid_until",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
