# Generated by Django 6.0.7 on 2026-10-03 12:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("url_shortener", "0007_shortlink_deactivated_and_validity_window"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="visit",
            index=models.Index(
                fields=["visited_at"], name="url_shorten_visited_e1e4f8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="visit",
            index=models.Index(
                fields=["short_link", "visited_at"],
                name="url_shorten_short_l_981068_idx",
            ),
        ),
    ]
